### ISSUE TITLE
Hiding BottomNavigation Bar

### ISSUE THREAD

**Issue by navedar** [callstack/react-native-paper#1023]
How to **hide the BottomNavigation Bar** for a particular screen??

**Comment by netochaves** [comment]
I do not know if this is what you are looking for, but I made this snack with a code to hide the tab bar when changing the screen, i just render null instead of the tab bar when changing the state and use the onIndexChange to choose in which screen to hide.
https://snack.expo.io/ryKGEhgkH

The bottomTabNavigator does something like this [here](https://github.com/react-navigation/tabs/blob/38f3af945ec962e5f40fd4a0a09506a013fecaa5/src/navigators/createBottomTabNavigator.js#L83)

**Comment by Hirbod** [comment]
Not stale. Is there no other way to hide it? There is an option to hide it when the keyboard is open, can we achieve this with a prop too?

**Comment by navedar** [comment]
I figured out a work-around to get desired result.
By adding a **negative** `marginBottom` in `barStyle` prop everytime we need to hide it, controlled using a global state (redux)

Ex. `<BottomNavigation barStyle={this.props.hideBottomDock ? {marginBottom: -bottomDockHeight} : null}`

**Comment by suman-as** [comment]
Ex. <BottomNavigation barStyle={{ display: bottomTabVisibility ? 'flex' : 'none' }} />
