### ISSUE TITLE
FAB.Group multiple portals

### ISSUE THREAD

**Issue by AlexMachin1997** [callstack/react-native-paper#1042]
Hi,

So I've been using React-Native-Paper for a while now, it's been incredibly useful to use. However,

I'm experiencing a minor problem with the portal component. When I show the FAB.group initially it works fine, but when I trigger a dialogue component to appear the Fab.group icon can still be clicked as seen in the image below

![Screenshot_20190502_114102_com shoppinglistapp](https://user-images.githubusercontent.com/29917195/57070659-07b7e380-6cd0-11e9-9587-e62865e28e7d.jpg)

The problem is related to two portals being on screen at once, it's essentially getting confused. 

Is there a way to combat this?

**Comment by satya164** [comment]
You need to re-order your components to render in the order you expect them to appear

For example, if you want to render the `Dialog` on top of `FAB.Group`, you need to render `Dialog` after `FAB.Group`:

```js
<Portal><FAB.Group /></Portal>
<Portal><Dialog /></Portal>
```

It follows the same rule as rendering absolutely positioned views in React Native. Imagine if you had `<View style={{ position: 'absolute' }}>` instead of `<Portal>`, and the behaviour you'd expect.

In your example, the dialog shouldn't appear on the top. The reason you can see the dialog at the top here is only because of how Android handles elevation style natively, which is a quirk we can do nothing about. This code will behave as expected on iOS.

**Comment by AlexMachin1997** [comment]
So how would I counter this issue? I'm sure many other people have had this issue and It would be great to hear how to solve.
