### ISSUE TITLE
Appbar.Header with ImageBackground support

### ISSUE THREAD

**Issue by lpasquini** [callstack/react-native-paper#1056]

**Comment by Taym95** [comment]
Can you add a description, please?

**Comment by kodayashi** [comment]
Hey @Taym95 - I'd like to expand on this actually. I think a broader solution would be to allow for a renderBackground that accepts an arbitrary component for the background. For example, @lpasquini wants the Appbar.Header to have an image background, but in my case I'd like to pass in a LinearGradient component so that the background isn't a solid color (but instead a gradient). Currently, this isn't possible.

**Comment by tiendn** [comment]
> After looking at the source, I realized (at least in my case) I could set the background color as transparent for <Appbar.Header ... /> and wrap it in a LinearGradient component. Works fine!

So with `ImageBackground` we can solve the problem of @lpasquini, right? 
Maybe we need an option with wrapper component like `<Appbar.Header wrapComponent={} ... />`

**Comment by lukewalczak** [comment]
Exactly, you can wrap your `AppHeader` within `ImageBackground` from react-native. [Here](https://snack.expo.io/@happiryu/imagebackgroundinheaderexample) you can check my example
