### ISSUE TITLE
Radio Buttons not working for Platforms when in groups. Also unable to use on select on agnostic buttons outside group.

### ISSUE THREAD

**Issue by rjerue** [callstack/react-native-paper#1117]
## Environment

Android, iOS, Web

## Description

On Android, iOS, and web RadioButton.Android and RadioButton.IOS do not render any sort of selection. Only the regular "RadioButton" seems to work in groups. Outside groups. No onPress seems to register for the agnostic RadioButton, but .IOS and .Android work as expected.

## Reproducible Demo

See the following Snack https://snack.expo.io/@rjerue/radiobutton.group

**Comment by evantrimboli** [comment]
Seems to be because of these lines:

https://github.com/callstack/react-native-paper/blob/d3db78f926eacb3c667846b7c9dcae8c5cdcf89e/src/components/RadioButton.tsx#L117

https://github.com/callstack/react-native-paper/blob/d3db78f926eacb3c667846b7c9dcae8c5cdcf89e/src/components/RadioButton.tsx#L135

Proposed changes:

Not sure of the intent here, but if the user has both an onPress and a context it doesn't seem like it would be harmful to call both. There are also conditional checks for a context, so we need to take that into account.
```
handlePress = (context: RadioButtonContextType) => {
  const { onPress, value } = this.props;
  if (onPress) {
    onPress(value);
  }
 if (context && context.onValueChange) {
   context.onValueChange(value);
 }
};
```

Don't bother with the context check here, just handle it in the callback.
```
onPress={() => this.handlePress(context)}
```

**Comment by abdullah-sr** [comment]
Having the same issue.

**Comment by jandrell-formoso** [comment]
Same issue. Need to use `RadioButton.Android` also on iOS.

**Comment by Trancever** [comment]
#1223 is going to fix this issue. It's closed to be merged so it should be released in next week probably.

**Comment by Justin2997** [comment]
Having the same issues. I expect `value` to also do the Label at the left of the Radio button seems like this is not showing. Maybe the document should be clearer because the screen shot are confusing with the code : https://callstack.github.io/react-native-paper/radio-button.html.
