### ISSUE TITLE
[New Features] Datatable column width and text style for title and cell.

### ISSUE THREAD

**Issue by cristinaITdeveloper** [callstack/react-native-paper#1150]
## Describe the feature

Give the possibility to set the width of the columns with the percentages and pass the style of the text for the title and the cells

## Motivation

I have some columns that have a lot of text and I would like them to be wider than the columns that have, ad example, only numbers, so that the text can be seen correctly.
Also give the possibility to set the number of lines of the text within the cells and the style of the text of the title and the cells, now in case I want to put the text centered, I can't.
Thank you

## Related Issues

No related issues

**Comment by MakhouT** [comment]
I agree with this feature request, it would be nice to be able to pass in props to configure this.

**Comment by wasim-abuzaher** [comment]
I would love to have this feature as well

**Comment by mmarkusik** [comment]
Hey @cristinaITdeveloper. I opened a pull request with the feature you proposed. Unfortunately we cannot add the `numberOfLines` prop because it's not consistent with the guidelines. As for the percentages for cell width there is a `style` prop on the cell component, to which you can pass a style object with flex property, so you should be able to make your cells wider or narrower without using percentages.
