### ISSUE TITLE
Button does not reflect dark theme and disabled color

### ISSUE THREAD

**Issue by alesdvorakcz** [callstack/react-native-paper#1156]
I hope I understand `dark` boolean in theme corretly. When I set it to true and choose dark primary color I expect white/light text on "contained" button. But it does not work.
I need to set specifically dark boolean at all buttons.

As workaround I created wrapper component with `dark={true}` by default but I think its not correct behavior am I right?

Similar problem is `disabled` color from theme. It looks like it has no effect for buttons. How can I set background/text color in disabled state?

I am using version 2.16.0

**Comment by satya164** [comment]
The text if the contained button depends on the background color of the button, which is automatically determined based on of the background color is light it dark. Wherever theme is dark or not doesn't affect it.

This is the desired behavior. We don't want to show white text on a light background because you have a dark theme, otherwise the text won't have enough contrast and will be illegible.

**Comment by alesdvorakcz** [comment]
Ok I understand I just expected setting dark theme will do the same as setting dark at all buttons. Thanks for info

**Comment by toby-pondr** [comment]
This was confusing for me as well. Perhaps documenting this would be helpful.
