### ISSUE TITLE
Animations and gestures, future development

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1288]
I'm considering RNP as component lib for my app. Everything seems very neat and well thought out. I like it!

I do wonder if you have any plans on implementing more animations, or is this deliberately left to the users? As an example I would like to animate the Accordion. What would be your suggested way of doing this?
- In a forked/inherited component?
- As a PR to the lib?

What animation and gesture library do you plan on using going forward. The hype right now seems to be gesture-handler and reanimated, but I saw that you opted out of gesture-handler due to it being non accessible #703.

**Comment by jaysbytes** [comment]
The goal of this library is to deliver components that follow Material UI guidelines. I think we are not going to implement animations that are not common for Material UI. But If you see any missing animation according to the MUI docs please open a new issue with a feature request. I'm not sure about accordion animation, for now, I cannot find anything in docs, but I'm for adding an animation

**Comment by wardjk87** [comment]
@jaysbytes is there any openness for PRs adding animation functionality to react-native-paper?

**Comment by wardjk87** [comment]
I've also created a search bar with chip functionality based on material design specs. I also have created a swipeable list item that using material design animations.

**Comment by jayu** [comment]
We would like to have any animation that fits into Material Design guidelines. So i.e things like swipeable list items should not be included in the library. It would probably add more dependencies and this feature 
 can be implemented by end-user with other libraries. But animated accordion is a nice to have thing, because this animation cannot be easily added to accordion by end user, and animated accordion is that kind of user experience practice, that app user would expect to have IMO. I believe this is a kind of standard, to have an animation for elements that can be expanded. 
On the other hand, actual implementation might be tricky and we might not want to have a hacky solution in paper's codebase, because someone has to maintain it later. In the case of accordion, `react-native` `LayoutAnimation` is worth trying https://facebook.github.io/react-native/docs/layoutanimation. It is not a perfect solution, but it might help in some cases.

**Comment by kopax** [comment]
> I've also modified the react-native-paper search bar to add chip functionality based on material design specs. I also have created a swipeable version of react-native-paper list item and react-native--swipe-list-view based on the material design animations.

Hello, it would be nice to see the swipeable version of react-native-paper.

Also, I was looking how to animate the collapse and landed here. Thanks for your solution @wardjk87, do you have a snack example we can see? (or GitHub repo)
