### ISSUE TITLE
Master branch has a failing test?

### ISSUE THREAD

**Issue by GollyJer** [callstack/react-native-paper#1309]
I'm having a heck of a time trying to submit a PR. 😀

This failure happens on a fresh copy of Master.
- Fork
- Clone
- `yarn bootstrap`
- `yarn test`

![image](https://user-images.githubusercontent.com/689204/63817954-91309880-c8f3-11e9-9215-87fac627c1af.png)

Not sure what to do. Is it only me?

**Comment by jaysbytes** [comment]
Yes, it is because of a different paths schema on Windows. We can fix it by adding a condition based on NodeJS `os`

`./src/babel/__tests__/index.js`

```js
const os = require('os');

// [...]

if (os.type() === 'WINDOWS_NT') {
      // use different fixtures for Windows
}
else {
     fixtures('generate mappings', path.join(__dirname, '..', '__fixtures__'));
}
```
I will require to have a Windows machine and create actual fixtures.
Based on docs of lib we use for this test `babel-test` it should have `code.js` file and `output.js` file
______________________________________________
From docs 

To run the tests against a directory with fixtures, you can use the `fixtures` function returned from `create`:

```js
fixtures('my plugin', path.join(__dirname, '__fixtures__'));
```

It accepts a title for the `describe` block and the absolute path to the directory containing the fixtures.

The fixtures directory should contain subdirectories with test files. Every test should contain a `code.js` file, which will be used as the input. If the transform should throw, it should have an `error.js` file. If the transform should pass, it should have an `output.js` file with the transformed code. The title for each test will be based the name of the directory. The first argument is used as the title for the describe block.

```sh
.
├── function-expression
│   ├── code.js
│   └── output.js
├── invalid-syntax
│   ├── code.js
│   └── error.js
└── simple-variable
    ├── code.js
    └── output.js
```

**Comment by GollyJer** [comment]
Done. 👍
https://github.com/callstack/react-native-paper/pull/1323
