### ISSUE TITLE
 Require cycle

### ISSUE THREAD

**Issue by ilibilibom** [callstack/react-native-paper#1520]
Hi 
I'm getting a require cycle warning from the radio RadioButton componenet:  
```
: node_modules/react-native-paper/lib/module/components/RadioButton/RadioButton.js -> node_modules/react-native-paper/lib/module/components/RadioButton/RadioButtonItem.js -> node_modules/react-native-paper/lib/module/components/RadioButton/RadioButton.js
```
Why is this happening ?

**Comment by Trancever** [comment]
@ilibilibom We have cycle dependencies in our codebase, but it's not causing any issues. Metro warns about them, but you can safely silent them with `YellowBox.ignoreWarnings(['Require cycle:']);`. We know that it's not a perfect solution, but we don't want to change our working architecture, because other tool don't like it.

**Comment by ilibilibom** [comment]
ok - where do I set this ? 
```
YellowBox.ignoreWarnings(['Require cycle:']);
```

**Comment by Trancever** [comment]
@ilibilibom Probably the best place is top of the index.js or whatever your entry point is. Also, please import YellowBox from react-native before.

**Comment by ilibilibom** [comment]
ok Thanks
