### ISSUE TITLE
Example Snack does not Show Icons

### ISSUE THREAD

**Issue by joshglenn** [callstack/react-native-paper#1532]
In this example snack, icons are not present. On web, they do not display at all. On the android test, they all. show up as question marks.

https://callstack.github.io/react-native-paper/appbar-header.html

**Comment by Trancever** [comment]
@joshglenn Would you like to submit a PR?

Changes have to be made in [this](https://github.com/callstack/react-native-paper/blob/master/src/components/Appbar/AppbarHeader.tsx) file.

`icon` prop on line 78 should be `"magnify"` instead of `"search"`
`icon` prop on line 79 should be `"dots-vertical"` instead of `"more-vertical"`

**Comment by joshglenn** [comment]
@Trancever thank you for the reply. To test, I made those changes to the snack. It works on the Android preview, but not on the Web. Is that expected behavior?

here's [the snack](https://snack.expo.io/@highoctane/appbar.header)

**Comment by Trancever** [comment]
@joshglenn So for web, we would have to somehow provide fonts containing these icons. I will look into it tomorrow.  

You can submit a PR anyway if it works on Android
