### ISSUE TITLE
Add support for Rating component 

### ISSUE THREAD

**Issue by asif-ir** [callstack/react-native-paper#1549]
## Motivation
I was using this library but it lacked a simple rating component which is usually present in every material based UI libraries. I had to implement a simple component for personal use. Instead of needing standalone rating libraries which raise the bundle sizes too much, we can provide a small component for this purpose under this module itself for general use, just like other component libraries.

**Comment by asif-ir** [comment]
I raised the #1550 PR implementing this.

**Comment by Trancever** [comment]
@asif-ir We try to follow MD Guidelines very strictly and only provide components that are described in the guidelines. Since I can't find any information about "Rating" component in the guidelines, I am closing this.
If you want to reuse this in other projects etc. consider making a library. It won't add any additional overhead since it will be only one file with only peer dependencies.
