### ISSUE TITLE
RadionButton missing Material Design Icons family font on iOS

### ISSUE THREAD

**Issue by IgorDePaula** [callstack/react-native-paper#1657]
## Environment

"react": "16.9.0",
 "react-native": "0.61.5",
 "react-native-paper": "^3.6.0",

## Description

I put a radiobutton element on screen and I received error of missing font family Material Design Icons

![Captura de Tela 2020-02-09 às 20 04 01](https://user-images.githubusercontent.com/2833993/74111979-9e76d200-4b77-11ea-9929-f9a47ac34faa.png)

## Reproducible Demo

![Captura de Tela 2020-02-09 às 20 04 37](https://user-images.githubusercontent.com/2833993/74111983-a767a380-4b77-11ea-8070-e2d2040c3a04.png)

**Comment by lindboe** [comment]
I had the issue of fonts not showing up properly with Checkbox on either iOS or Android. I solved it by adding the following to Info.plist:

```
<array>
  <string>AntDesign.ttf</string>
  <string>Entypo.ttf</string>
  <string>EvilIcons.ttf</string>
  <string>Feather.ttf</string>
  <string>FontAwesome.ttf</string>
  <string>FontAwesome5_Brands.ttf</string>
  <string>FontAwesome5_Regular.ttf</string>
  <string>FontAwesome5_Solid.ttf</string>
  <string>Foundation.ttf</string>
  <string>Ionicons.ttf</string>
  <string>MaterialIcons.ttf</string>
  <string>MaterialCommunityIcons.ttf</string>
  <string>SimpleLineIcons.ttf</string>
  <string>Octicons.ttf</string>
  <string>Zocial.ttf</string>
</array>
```
And following these steps for Android from react-native-vector-icons: https://github.com/oblador/react-native-vector-icons#option-with-gradle-recommended.

Both of these are (basically) listed in the install instructions for react-native-vector-icons, but I didn't think to look there since the "Getting Started" guide for react-native-paper just suggested commands to run (and `link` is typically unnecessary for this version of RN).

I would suggest updating the documentation to just point people to react-native-vector-icons instructions on how to install the library instead of writing out the example installation command.

**Comment by IgorDePaula** [comment]
> I had the issue of fonts not showing up properly with Checkbox on either iOS or Android. I solved it by adding the following to Info.plist:
> 
> ```
> <array>
>   <string>AntDesign.ttf</string>
>   <string>Entypo.ttf</string>
>   <string>EvilIcons.ttf</string>
>   <string>Feather.ttf</string>
>   <string>FontAwesome.ttf</string>
>   <string>FontAwesome5_Brands.ttf</string>
>   <string>FontAwesome5_Regular.ttf</string>
>   <string>FontAwesome5_Solid.ttf</string>
>   <string>Foundation.ttf</string>
>   <string>Ionicons.ttf</string>
>   <string>MaterialIcons.ttf</string>
>   <string>MaterialCommunityIcons.ttf</string>
>   <string>SimpleLineIcons.ttf</string>
>   <string>Octicons.ttf</string>
>   <string>Zocial.ttf</string>
> </array>
> ```
> 
> And following these steps for Android from react-native-vector-icons: https://github.com/oblador/react-native-vector-icons#option-with-gradle-recommended.
> 
> Both of these are (basically) listed in the install instructions for react-native-vector-icons, but I didn't think to look there since the "Getting Started" guide for react-native-paper just suggested commands to run (and `link` is typically unnecessary for this version of RN).
> 
> I would suggest updating the documentation to just point people to react-native-vector-icons instructions on how to install the library instead of writing out the example installation command.

This resolve my problem, thanks.
