### ISSUE TITLE
useNativeDriver is required in Animation.Timing calls in newer versions of React Native

### ISSUE THREAD

**Issue by ryanmagoon** [callstack/react-native-paper#1678]
## Describe the feature

in Animated for react native v62+, `useNativeDriver` is a required value. I saw this in particular for `onPressIn` and `onPressOut` for the `Button` component.

![image](https://user-images.githubusercontent.com/5327290/74630552-d1e1cf80-5128-11ea-929e-f53d7e42820e.png)

## Motivation

getting rid of yellow box errors on day one when 62 comes out fully

**Comment by ahmetbicer** [comment]
Same problem here. Would be great if we get a fix.

**Comment by hakimhassani97** [comment]
hi @ryanmagoon ,
a faced the same problem as you  
i'm on  
`"react-native": "0.62.0",`
`"react-native-paper": "^3.6.0",`

for me the problem was on **Button** with `mode='contained'`
so my work around was to :
- remove the `mode` prop
- use a custom style
`style={{backgroundColor:Theme.primary, elevation:7, border:0}}`
- set text color, which changes the **ripple effect's color**
`color={Theme.light}`
and now the **Button** animations work without warnings
😃

**Comment by abgaryanharutyun** [comment]
I have some problem too.

Waiting for update. Thanks

**Comment by azuxx** [comment]
Same problem too and proposed workaround does not work, I have this error:

![Screenshot 2020-04-07 at 10 04 56](https://user-images.githubusercontent.com/16132913/78645225-7970b800-78b7-11ea-8cc1-890dc12886e7.png)

**Comment by Trancever** [comment]
Fixed in v3.8
