### ISSUE TITLE
Button color rendered different from it's code

### ISSUE THREAD

**Issue by cryptozoidberg** [callstack/react-native-paper#1731]
## Environment

React Native 0.61
React Native Paper 3.6.0
## Description

I can't get my buttons to look exactly what I want it looks. 
Expected color: 66b1f9
Result color(picked from screen): 77B1F3

## Reproducible Demo

import * as React from 'react';
import { Button } from 'react-native-paper';
import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';

const theme = {
  ...DefaultTheme,
  roundness: 4,
  colors: {
    ...DefaultTheme.colors,
    primary: '#66b1f9',
  },
};

const MyComponent = () => (
  <PaperProvider theme={theme}>
    <Button icon="camera" mode="contained" onPress={() => console.log('Pressed')}>
      Press me
    </Button>
  </PaperProvider>
);

export default MyComponent;
`
Here is the link to snack: https://snack.expo.io/ByCEuxPSI 

<img width="602" alt="problem_in_paper" src="https://user-images.githubusercontent.com/7261328/76474257-58719000-63fb-11ea-9264-832cce5e5fdb.png">

**Comment by eightyfive** [comment]
Same problem here. `Button` is not picking up custom `primary` color. Only `Button` component afaik, the rest do reflect the new `primary` color.

```json
"react-native": "0.61.5",
"react-native-paper": "^3.6.0"
```

**Comment by eightyfive** [comment]
Ok after a bit of digging and playing with [Theming](https://callstack.github.io/react-native-paper/theming):
```js
// ¡ KO
function Button({ theme, ...rest }) {
  // Note: Actually logs the default Theme values.
  console.log('THEME', theme);

  return <PaperButton {...rest} theme={theme} />;
}

export default withTheme(Button);

// OK !
import Theme from '../theme';

export default function Button(props) {
  return <PaperButton {...props} theme={Theme} />;
}
```

**Comment by pan-pawel** [comment]
Hello @cryptozoidberg and @eightyfive Thanks for messages.
Can you provide more info how to reproduce ?
When I open snack i have
![Screenshot from 2020-04-19 21-13-11](https://user-images.githubusercontent.com/3886886/79697403-f3734a80-8282-11ea-8341-1f15e0092da1.png)
`rgb(102,177,249) = #66b1f9` so it looks correct

**Comment by pan-pawel** [comment]
Also, I even run my mac to check this tool that You are using.
Isn't it weird?
<img width="1013" alt="Screenshot 2020-04-19 at 21 28 58" src="https://user-images.githubusercontent.com/3886886/79697870-7eeddb00-8285-11ea-85de-1825c6dc2a2a.png">
<img width="1013" alt="Screenshot 2020-04-19 at 21 29 41" src="https://user-images.githubusercontent.com/3886886/79697875-83b28f00-8285-11ea-9c21-fb03448ac118.png">
So I checked with graphic editor
<img width="1115" alt="Screenshot 2020-04-19 at 21 31 48" src="https://user-images.githubusercontent.com/3886886/79697887-97f68c00-8285-11ea-8fd8-0601dd5d785b.png">
Are you sure that components shows invalid color ? because for me it looks like the problem is in the color picker that you are using. 🧐

**Comment by cryptozoidberg** [comment]
Hi @pan-pawel, thanks for your response! 
I actually don't know why exactly I'm having that issue. The problem also appears on my physical ios device when I run react-native code. Well, I can live with that, I thought maybe I did something wrong on my side and it might be obvious from that example.
