### ISSUE TITLE
After upgrading to React Native 0.62 a warning is showing

### ISSUE THREAD

**Issue by yankovalera** [callstack/react-native-paper#1781]
## Environment
React Native 0.62
react-native-paper 3.7.0

## Description
After upgrading my app to React Native 0.62 I'm getting a warning 

%s: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. ReactNativeFiberHostComponent

I've tracked down and seems to be a problem with react-native-safe-area-view dependency

## Reproducible Demo
- Create a new RN 0.62 app
- Add react-native-paper
- Run the app, the warning shows.

**Comment by pan-pawel** [comment]
@yankovalera Thanks for your message!
Can you provide more info?
I tried to install clean `0.62 `RN with `3.7.0` react-native-paper
I used modal and bottom-navigation (they both uses safe-area-view)
And i cannot see warning.
Also, i checked that paper in 3.7.0 uses safe-area-view 
https://github.com/callstack/react-native-paper/blob/73814f8bb4b0e75bafe5ad5a088962e3d6ef0480/package.json#L50

and safe-area-view with this version contain if for `getNode()`
https://github.com/react-native-community/react-native-safe-area-view/blob/84749ae2fc6ffefa2933d2845efa43ced0bf6cfc/src/index.tsx#L108-L111

Can you check what version of safe area view you have? also can you check how safe area view index.js in your node_modules looks like? for me it's
`const node = typeof this.view.measureInWindow === 'function' ? this.view : this.view.getNode();`

![Screenshot from 2020-04-19 19-36-25](https://user-images.githubusercontent.com/3886886/79696342-6927e800-827c-11ea-90a3-d681568543e1.png)
Modal:
![Screenshot from 2020-04-19 19-36-34](https://user-images.githubusercontent.com/3886886/79696343-6a591500-827c-11ea-816f-d9a5d74fc024.png)
Bottom Navigation
![Screenshot from 2020-04-19 19-36-44](https://user-images.githubusercontent.com/3886886/79696344-6a591500-827c-11ea-9660-8fe90c31491b.png)

**Comment by yankovalera** [comment]
Hi @pan-pawel, it's using react-native-safe-area-view "0.14.8". The warning shows in the screen that I'm using the createMaterialBottomTabNavigator 

Definitely index.js looks different, mine says

```this.view.getNode().measureInWindow((winX, winY, winWidth, winHeight) => ````

Looks like it has been solved here? https://github.com/react-native-community/react-native-safe-area-view/pull/110

Thanks!

**Comment by andreialecu** [comment]
https://github.com/callstack/react-native-paper/blob/master/package.json#L50

Indeed, the `react-native-safe-area-view` is pinned to `^0.14.6`, so the fix from https://github.com/react-native-community/react-native-safe-area-view/pull/110 isn't available.

react-native-paper needs to update that dependency it seems like.

**Comment by andreialecu** [comment]
It seems that a bit more thought needs to go into this instead of simply updating package.json.

Newer versions on `react-native-safe-area-view` use require also adding a dependency to `react-native-safe-area-context` as per the [README](https://github.com/react-native-community/react-native-safe-area-view#installation).

However, both provide the same `SafeAreaView` component. Also see this related issue:
https://github.com/react-native-community/react-native-safe-area-view/issues/99

`react-native-paper` is used by react-navigation v5, and they [recommend in their docs](https://reactnavigation.org/docs/handling-safe-area/) to use [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context).

This makes the proper solution a bit confusing. I think perhaps `react-native-paper` should add a peer dependency to `react-native-safe-area-context` and update the documentation to suggest installing it manually.

To make things worse, it seems that the react-native built-in `SafeAreaView` is also used in certain components: https://github.com/callstack/react-native-paper/search?q=safeareaview&unscoped_q=safeareaview

**Comment by benoitdion** [comment]
I attempted to fix this with https://github.com/callstack/react-native-paper/pull/1448 a while back but it seems the maintainers want to go a different direction
