### ISSUE TITLE
Is there a way to control Banner text content vertical align?

### ISSUE THREAD

**Issue by mogarick** [callstack/react-native-paper#1804]
## Ask your Question

I'm trying to align the text content vertically without any luck. The text keeps showing top aligned.

Heres is a snack [link](https://snack.expo.io/@tuukul/6a0e04)

**Comment by mciechanowicz** [comment]
I'm not sure if your are able to  center the text with the icon. Those components are nested in View with their own styling.

**Comment by Trancever** [comment]
@mogarick What's wrong with default alignment? That's what MD Guidelines recommend and we want to strictly follow the rules, that's why it's not possible to change it.

Btw. in your snack you can use the Icon component from vector icons instead of IconButton. Only the action buttons at the bottom of the banner should be pressable.
