### ISSUE TITLE
Call components as methods

### ISSUE THREAD

**Issue by cospin** [callstack/react-native-paper#1898]
## Is it possible to call some components as methods?
For example, I wish I could call: `Banner.show({...props}`), `Dialog.show({...props})`, `Modal.show({...props})` and `Snackbar.show({...props})`, so I can fire it easily on callbacks, etc.

Is there any example or advice to achieve something like that?

Thanks!

**Comment by macfanatic** [comment]
Not that I could find: I ended up creating a react context and mounting that at the root of my app components, to render a Snackbar when triggered globally.

This allowed me to use the context from anywhere in my codebase, to dispatch an action via the reducer on the global react context I made, and have the state change so that the snackbar component was rendered.

I think the same concept could be applied to the other components.

Snack example showing the provider at the root, the custom component inside the provider, and a child component using the global react context to dispatch an action that ultimately changes the state on the snackbar component to be presented.

https://snack.expo.io/@macfanatic/react-native-paper-snackbar-provider
