### ISSUE TITLE
TextInput: "Malformed calls from JS: field sizes are different."

### ISSUE THREAD

**Issue by netbull** [callstack/react-native-paper#2117]
### Current behaviour

When TextInput is focused "Malformed calls from JS: field sizes are different." exception is thrown.

### Code sample

Just standard usage of TextInput /even with default props/.

### Screenshots (if applicable)

N/A

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 13.6
| react-native          | 0.63.2
| react-native-paper    | 4.0.1
| node                  | 10.19.0
| npm or yarn           | yarn  1.22.0
| expo sdk              | n/a
|react-native-vector-icons | 7.0.0

**Comment by netbull** [comment]
The issue was from another library, sorry!

**Comment by DavidUnzue** [comment]
Hey @netbull I'm facing the same issue as you and unable to find a solution. Would you mind telling more about how you fixed it and what was the library that was causing the issue?

**Comment by DavidUnzue** [comment]
Nevermind, I found out the my issue was caused by the external library [react-native-input-scroll-view](https://github.com/baijunjie/react-native-input-scroll-view). It seems the issue there was fixed [here](https://github.com/baijunjie/react-native-input-scroll-view/pull/73). As a rule of thumb I would recommend checking all your external dependencies for compatibility with the latest RN version.

**Comment by netbull** [comment]
@DavidUnzue sorry for the no reply :/ I'm not into RN development since few months now and is quite hard to remember what was the cause.. 

However I'm glad that you figured out what the issue was!
