### ISSUE TITLE
TextInput lineHeight and letterSpacing support?

### ISSUE THREAD

**Issue by creambyemute** [callstack/react-native-paper#2289]
Hey there!

I got a question about the TextInput Component: 
Does it not support custom lineHeight and letterSpacing? I had a quick glance at the code and it doesn't look like it does.

* Do you think this should be supported
* Are there reasons why it isn't supported yet on TextInput but is on the Typography components?

Versions:
* react-native  0.62.2
* react-native-paper 2.16.0 (Yeah I know, pretty outdated!)
* react-native-vector-icons 6.6.0

**Comment by creambyemute** [comment]
Yes, because it's not in the source code

**Comment by latobibor** [comment]
Hi!

  It is still not available in...

**Versions:**
* `react-native`: 0.63.4
* `react-native-paper`: 4.7.2
* `react-native-vector-icons`: 8.0.0

 I have managed to have an ugly workaround:
```jsx
<Button mode="contained" uppercase={false} onPress={login} loading={isLoggingIn}>
  <Text style={{ letterSpacing: 0.5 }}>{content.login.button}</Text>
</Button>
```

Otherwise my UI would look very inconsistent:
![image](https://user-images.githubusercontent.com/12050526/108722897-ed459e80-7523-11eb-8731-773c1817f9a2.png)

**Comment by Ankit-sagar32** [comment]
Still this issue not resolved?

**Comment by mengnans** [comment]
any updates for this one
