### ISSUE TITLE
How to add custom elements to TextInput left or right

### ISSUE THREAD

**Issue by carltian** [callstack/react-native-paper#2305]
`<TextInput
// label={label}
value={val}
style={this.styles.TextInput}
placeholder={placeholder}
left={
<TextInput.Icon
color="#8C8C8C"
icon="lock"
size={30}
/>
}
right={
<Button mode="outlined" disabled={hasPhone} compact>
                    "confirm"
                </Button>
}
secureTextEntry={isPwd}
onChangeText={(text) =>
this.setText(text, filed)
}
/>
`
**Left can be show Element, but right can't.**

 "react-native": "0.63.2",
 "react-native-paper": "^4.1.0",
 "react-native-vector-icons": "^7.1.0",

**Comment by arthurpankiewicz** [comment]
bump

**Comment by STonkoshkur** [comment]
The same problem. 'Right' can render only TextInput.Icon or TextInput.Affix and nothing else. Looks like [TextInputAdornment](https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/Adornment/TextInputAdornment.tsx) component deny that. Can it be fixed?

**Comment by RichardLindhout** [comment]
Left and right are supported: https://snack.expo.io/U!Gg8T2aQ

Only TextInput.Icon and TextInput.Suffix are supported not a Button component and I never see it in the Material Design Spec
https://material.io/components/text-fields#filled-text-field
![unnamed (3)](https://user-images.githubusercontent.com/6492229/99876189-6ec02480-2bf5-11eb-95dc-160d44c4730d.png)

It will also take a lot of space on mobile, maybe search for an alternative layout with a Button below the TextInput instead of inside the TextInput.

**Comment by arthurpankiewicz** [comment]
https://material-ui.com/components/text-fields/#input-adornments

You've never seen a button icon to reveal the password in a TextInput?

**Comment by RichardLindhout** [comment]
Yes, but you can do that with react-native-paper I updated my Snack
https://snack.expo.io/3WcRzyask
```
<TextInput left={<TextInput.Affix text="hello"/>} right={<TextInput.Icon icon="password" onPress={()=>alert('show password')}/>} />
```

**Comment by RichardLindhout** [comment]
If it fixed it for you can you close the issue?

**Comment by Trancever** [comment]
Thanks @RichardLindhout for providing the example 👍 We should update `TextInput.Icon` and `TextInput.Affix` docs, I will create a separate issue

**Comment by kaime** [comment]
Why don't just allow any component to be passed as `left` or `right`? I'd like to place a non-clickable icon on the left of an `<TextInput>`:

![image](https://user-images.githubusercontent.com/445766/101243094-2416d000-36fe-11eb-837b-7699b1980488.png)

But it won't work because the `TextInputAdornment` function won't render any element that's not an `AdornmentType.Icon` or an `AdornmentType.Affix`:

``` js
if (type === AdornmentType.Icon) {
  return (
    <IconAdornment ... />
  );
} else if (type === AdornmentType.Affix) {
  return (
    <AffixAdornment ... />
  );
} else {
  return null;
}
``` 

If a just use a `<TextInput.Icon>` without an `onPress` prop, then I get an `<IconButton>`, which will receive cursor events and show a ripple when tapped.

**Comment by gmonte** [comment]
I resolved the problem using the `render` prop and styled-components, like that:

```js
import { TextInput } from 'react-native-paper'
import styled from 'styled-components/native'

const InputContainer = styled.View`
  flex-direction: row;
`
const Input = styled.TextInput`
  flex: 1;
`
const AdornmentContainer = styled.View`
  align-items: center;
  justify-content: center;
  padding: 0 10px;
`

const CustomInput = ({ left, right, ...props }) => (
  <TextInput
    { ...props }
    render={ (inputProps) => {
      <InputContainer>
        {left && (
           <AdornmentContainer>
             {left}
           </AdornmentContainer>
         )}
         <Input { ...inputProps } />
         {right && (
            <AdornmentContainer>
              {right}
            </AdornmentContainer>
          )}
      </InputContainer>
    } }
   />
)
```

Now I am able to render anything as "left" and "right".

**Comment by parmarravi** [comment]
I have one case in which there is a text button at the end of the textInput and it is clickable. Also, the text has a different color.

**Comment by MauriceNino** [comment]
I solved the problem using a wrapper `View` and placing the right item `absolute`, while simultaneously setting the real `right` prop to an empty element, so that the text does not overlap the custom right content.

This way, the text box does not get cut off like when using a flex container. You could apply the same logic for a `absoluteLeft` element.

```tsx
import React, { ComponentProps } from 'react';
import { TextInput as RNTextInput, View } from 'react-native';
import { TextInput as PaperTextInput } from 'react-native-paper';
import styled from 'styled-components';

const AbsoluteRightContainer = styled(View)`
  position: absolute;
  top: 0;
  right: 10px;
  height: 100%;
  justify-content: center;
`;

type TextInputProps = {
  absoluteRight?: JSX.Element;
};

export const TextInput = React.forwardRef<
  RNTextInput,
  ComponentProps<typeof PaperTextInput> & TextInputProps
>((props, ref) => {
  const theme = useTheme();

  const { absoluteRight, ...rest } = props;

  return (
    <View>
      <PaperTextInput
        ref={ref}
        right={absoluteRight ? <></> : undefined} // If an absoluteRight element is provided, pass a fake right element
        {...rest}>
        {props.children}
      </PaperTextInput>
      <AbsoluteRightContainer>{absoluteRight}</AbsoluteRightContainer>
    </View>
  );
});
```

**Comment by JoaoMosmann** [comment]
I'm trying to render a clickable text emoji on the left prop, however, it seems I'll have to use one of the suggested workarounds. But it would be great if the `left` and `right` props could accept any component

**Comment by Teut2711** [comment]
So, how can I create a TextInput field for mobile number? I want 

```js
 <TextInput
          left={<>
              <TextInput.Icon icon="phone" />;
              <TextInput.Affix text="+91" />
</>          )}
```

**Comment by umang3105** [comment]
How can i get both icon as well as text on the right?


I am implementing username input. so if its available i render available in <TextInput.Affix text="Available"/>. But i also need to render <TextInput.Icon/> along with that
