### ISSUE TITLE
After importing react-native-paper: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle

### ISSUE THREAD

**Issue by santanubiswascispl** [callstack/react-native-paper#2336]
Versions:
-----------------
react-native: 0.63.2
react-native-paper: 4.2.0
react-native-vector-icons: 7.1.0

![image](https://user-images.githubusercontent.com/62833421/97993938-bdef1280-1e0a-11eb-96f9-4739a5558fde.png)

**Comment by davwheat** [comment]
Yes, it does.

**Comment by itallolegal** [comment]
same here

**Comment by samOpenforce** [comment]
I am also receiving the require cycles warning. Package versions as follows:

- `react-native`: `0.63.3`
- `react-native-paper`: `4.4.0`
- `react-native-vector-icons`: `7.1.0`

**Comment by RichardLindhout** [comment]
This warning has no real life implications other than make the console cluttered.

This warnings shows up because react-native-paper supports things like Fab.Group, RadioButton.Group where the radiobutton or fab will import the group component

@unikvozm maybe we could prevent this if components like FAB and FABGroup but an extra file with FABexports.ts
with

```
import FABGroup from './FABGroup';
import FAB from './FAB';
FAB.Group = FABGroup;
export { FAB, FABGroup }
```

**Comment by unikvozm** [comment]
@RichardLindhout, thanks for putting my attention to it, I’ll take a close look on Monday.

**Comment by unikvozm** [comment]
The fixes are merged and will be available in the next release soon =)
