### ISSUE TITLE
How to change overlay color button?

### ISSUE THREAD

**Issue by jordyandreas** [callstack/react-native-paper#2341]
Hi, I'm using Dialog for pop up alert on my apps.
but there's something bothering me about the overlay color button after onPress and it's color purple.
how to change that overlay color on button after onPress? I want to change it to transparent or maybe white/grey.

React native version: 0.60.5
React native paper version: 4.1.0

here's my code:
`<Dialog visible={this.props.visible} dismissable={false}>
                    <Dialog.Title>{this.props.title}</Dialog.Title>
                    <Dialog.Content>
                        <Paragraph>{this.props.content}</Paragraph>
                    </Dialog.Content>
                    <Dialog.Actions>
                        <Button onPress={() => this._pressCancel()}>{this.props.txtCancel}</Button>
                        <Button onPress={() => this._pressOk()}>{this.props.txtOk}</Button>
                    </Dialog.Actions>
                </Dialog>`

here's some image:
![image](https://user-images.githubusercontent.com/44167609/98096430-54304080-1ebe-11eb-85de-9e18817da88f.png)

already using the props style, using mode contained/outlined but no help.
the overlay color of button is purple, like default from RN paper. but I want to change it to transparent or maybe grey like ripple over TouchableOpacity.

Anyone can help me? please 
thanks in advance...

**Comment by RichardLindhout** [comment]
You can change the color of the ripple effect if you change the text color. The ripple effect will be the text color in 0.32 opacity.
It not possible to make the ripple color transparent since this would not follow the Material Design specifications.

```
<Button onPress={() => this._pressOk()} color="#000">{this.props.txtOk}</Button>
```

But I think the color of the buttons should be the primary theme color like the images on:
https://callstack.github.io/react-native-paper/dialog-actions.html

I don't see why the text color of the buttons is black, can you provide more info like your theme config and full code of the dialog?

Source of this answer:
https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L131
https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L220
https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L225
