### ISSUE TITLE
Add font-color control on Fab Group Labels

### ISSUE THREAD

**Issue by Joeao** [callstack/react-native-paper#2373]
**Is your feature request related to a problem? Please describe.**
Fab Group label colours can't be manually changed outside of the theme, and users of a light theme have the label text opacity set to `0.54`.

**Describe the solution you'd like**
I'd like to be able to have greater control over fab group label font-color by passing a color in to the styles property and having it affect the label color.

**Describe alternatives you've considered**
I'm currently passing in a modified theme in order to achieve a similar result, setting it to a dark theme to avoid the opacity change and setting the font-color to the one I desire.

```js
<Fab.Group
    theme={{
        ...myTheme,
        dark: true,
        colors: {
            ...myTheme.colors,
            text: '#000'
        }
    }}
```

**Additional context**
There's a [stale pull request](https://github.com/callstack/react-native-paper/pull/2096) removing the opacity change, but I figure that the forced opacity must be there for a reason. I'm happy to make a pull request to allow the user to pass in the font-color themselves. Otherwise it takes the existing theme's text color and keeps the opacity adjustment.

**Comment by Joeao** [comment]
I can, bot. But the issue template doesn't request these. 

`react-native: 0.63.3`
`react-native-paper: 4.4.0`
`react-native-vector-icons: 7.1.0`

**Comment by Joeao** [comment]
It's still a thing

**Comment by Joeao** [comment]
Good job

**Comment by johnny-minty** [comment]
I've got the same issue. There isn't a prop to control the label text color. 

![image](https://user-images.githubusercontent.com/6396138/116651663-c8fcb700-a9d7-11eb-8b6d-5340463a99cb.png)

**Comment by butterfly-valley** [comment]
Confirm the issues still persists

**Comment by justinjaeger** [comment]
This is a bit hacky but you can change the label text color by doing this:

`theme={{ colors: { text: 'black' }, dark: true }}`

This is because it determines labelColor specifically from the passed in theme.

Dark needs to be true, else it will be 50% opacity.

I really do wish there were options to customize the label though, because I'd like to have the option to make it bigger and add padding. Some styling for the FABs like marginBottom is useless because it stretches the label along with it, and you have no ability to edit the label to compensate
