### ISSUE TITLE
Searchbar component ignores numberoflines prop on iOS

### ISSUE THREAD

**Issue by alesdvorakcz** [callstack/react-native-paper#2398]
### Current behaviour
When setting numberoflines={1} to Searchbar component, it still shows multiple lines on ios.

### Expected behaviour

Only one line is visible

### Code sample

[https://snack.expo.io/mM73lZ7cL](https://snack.expo.io/mM73lZ7cL)

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1890782/101241348-23972d00-3730-11eb-997e-804e26f5f819.png)

### Your Environment
on snack:
expo: 39.0.0

and locally:
react-native-paper: 4.1.0
react-native: 0.63.2
ios 14.2

**Comment by jaworek** [comment]
Props are case sensitive and I see that you provided in your example `numberoflines`, instead of `numberOfLines`

It is only supported on Android:
https://reactnative.dev/docs/textinput#numberoflines

I'll let you know when I find solution for iOS.

**Comment by jaworek** [comment]
For iOS you can specify `inputStyle` with height. E.g. `inputStyle={{height: 40, alignSelf: "center"}}`

Here's an example:
https://snack.expo.io/HOZiyJZyX

**Comment by alesdvorakcz** [comment]
I did the mistake with sensitivity in snack only, but it does not work even with correct name.

Thank you for this workaround and for info its currently not supported. I usually set this to <Text /> component so I didn't realize its different here.

**Comment by IKTANIM** [comment]
For iOS  inputStyle={{textAlign: "auto"}} fixed my issue

**Comment by Saly-X** [comment]
> In the current version of react-native-paper, none of these solutions work. Any suggestions to fix it?

I've tested and played with the code of the `Searchbar` and `TextInput` in `react-native-paper`. The main affecting aspects are these styles of the TextInput inside the Searchbar: `lineHeight` in `font` and `textAlign: I18nManager.getConstants().isRTL ? 'right' : 'left'` in `input` style. Also, for `TextInput` with a `label`, we have only `one line` as expected.

I know, it's not a fix, this is a `workaround hack`, because we are resetting the library styles, but adding these lines to inputStyle helped for me:

```
textAlign: undefined,
lineHeight: undefined,
```

Also you can add these props just in case:
```
numberOfLines={1}
multiline={false}
```
