### ISSUE TITLE
Secondary color instead of "dark"

### ISSUE THREAD

**Issue by pshrmn** [callstack/react-native-paper#255]
I'm really enjoying `react-native-paper` so far. I was wondering, however, if some of the theme color properties could be improved.

### Current behaviour

The theme has both a color and a dark color (both "primary").

### Expected behaviour

The [Material Design guidelines](https://material.io/guidelines/style/color.html) uses `primary` and `secondary` colors. I think that a "primary" and "secondary" color would make more sense than default and "dark".

With the current setup, if the default theme _is_ dark, you either have to specify `dark` everywhere or use `dark` to refer to a light theme.

### Code sample

```jsx
const theme = {
  colors: {
    primary: '#234',
    secondary: '#def',
    primaryText: '#def',
    secondaryText: '#234'
  }
};

<Button secondary />
```

Alternatively, colors could be grouped under a key so that instead of a `dark` (or `secondary`) boolean prop, the theme key could be provided.

```jsx
const theme = {
  colors: {
    primary: {
      color: '#234',
      text: '#def'
    },
    secondary: {
      color: '#def',
      text: '#234'
    }
  }
};

<Button theme='secondary' />
```

### Screenshots (if applicable)

n/a

### What have you tried

n/a

### Your Environment

n/a

**Comment by satya164** [comment]
> The Material Design guidelines uses primary and secondary colors. I think that a "primary" and "secondary" color would make more sense than default and "dark".

We have a `default` and a `dark` theme because they are two different kind of themes and components need to adjust various things such as opacity of some colors depending on if it's a dark or light theme.

Whereas, primary and secondary (we call it accent in the theme) colors are meant to be used in a pair and the colors themselves don't other parts of component.

> The theme has both a color and a dark color (both "primary").

I don't understand what you mean here. Are you referring to `primaryDark`?

> With the current setup, if the default theme is dark, you either have to specify dark everywhere or use dark to refer to a light theme.

Can you describe a little more? All components adapt to the theme automatically. The `dark` prop accepted by some components is a for specific use cases, for example you have a light background color for a button, so you want to force the text color to be black etc., unrelated to what the theme is. So you shouldn't need to use it for dark theme support. Can you post some code where you need to do that so I can understand it better?

> Alternatively, colors could be grouped under a key so that instead of a dark (or secondary) boolean prop, the theme key could be provided.

Have you looked at the [theming guide](https://callstack.github.io/react-native-paper/theming.html)? You can pass an object for the theme prop, as well as switch the theme completely by using a `ThemeProvider` somewhere down the tree.

> `<Button theme='secondary' />`

This is unlikely to be supported since this won't work with static type checkers and we want the ibrary to be fully satically typable.

**Comment by pshrmn** [comment]
I think that if there was a concise explanation of each theme property in the documentation, their purpose would be a lot more clear. That was probably the biggest issue for me.

Taking a look with fresh eyes, I see that I misunderstood secondary colors while skimming the Material guidelines (secondary is really just an accent, not an alternative theme as I had first thought). Nested `<ThemeProvider>`s on pages that need an alternative theme should work well enough for what I was envisioning.

**Comment by pshrmn** [comment]
> The dark prop accepted by some components is a for specific use cases, for example you have a light background color for a button, so you want to force the text color to be black etc., unrelated to what the theme is. So you shouldn't need to use it for dark theme support. Can you post some code where you need to do that so I can understand it better?

The `<Toolbar>` appears to be an exception to this. If I have a theme whose `primary` color is dark, then I have to pass `dark={true}` to either the `<Toolbar>` or the individual children elements (it looks like `React.cloneElement` is used for `dark` prop injection) in order to get light text.

**Comment by satya164** [comment]
Can you open a new issue for that?

**Comment by pshrmn** [comment]
Superseded by #257
