### ISSUE TITLE
onValueChange in ToggleButton.Group is called with null

### ISSUE THREAD

**Issue by maxammann** [callstack/react-native-paper#2578]
Recreated from https://github.com/callstack/react-native-paper/issues/2452 as the last one was closed without any comment.

### Current behaviour

onValueChange in ToggleButton.Group is called with `null`

### Expected behaviour

I think it is fine to call it with null. In that case the TypeScript types need to be changed. We could also introduce a `defaultValue` prop which is used when no toggle button is selected.

### Code sample

[Snack](https://snack.expo.io/i5_NrJH5x?name=ToggleButton.Group&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ftoggle-button-group.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20{%20ToggleButton%20}%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20{%0A%20%20const%20[value%2C%20setValue]%20%3D%20React.useState(%27left%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CToggleButton.Group%0A%20%20%20%20%20%20onValueChange%3D{value%20%3D%3E%20setValue(value)}%0A%20%20%20%20%20%20value%3D{value}%3E%0A%20%20%20%20%20%20%3CToggleButton%20icon%3D%22format-align-left%22%20value%3D%22left%22%20%2F%3E%0A%20%20%20%20%20%20%3CToggleButton%20icon%3D%22format-align-right%22%20value%3D%22right%22%20%2F%3E%0A%20%20%20%20%3C%2FToggleButton.Group%3E%0A%20%20)%3B%0A}%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

```tsx
import * as React from 'react';
import { ToggleButton } from 'react-native-paper';

const MyComponent = () => {
  const [value, setValue] = React.useState('left');

  return (
    <ToggleButton.Group
      onValueChange={value => {setValue(value); alert(value);}}
      value={value}>
      <ToggleButton icon="format-align-left" value="left" />
      <ToggleButton icon="format-align-right" value="right" />
    </ToggleButton.Group>
  );
};

export default MyComponent;
```
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.4
|react-native-vector-icons| 8.1.0
| react-native-paper    | 4.7.2

**Comment by cavalos0086** [comment]
Any updates on this issue?  I am also having a very similar issue where the second tap on the same button will trigger the `onValueChange` with a `null` value. 

I have `react-native-paper`  on version 4.7.2 and `react-native-vector-icons` on version 8.1.0. 

Thanks

**Comment by lukewalczak** [comment]
Hey @maxammann, I guess you're right and we need to correct types, since value can be `null` when neither option is selected. Also I think there is no need to implement `defaultValue`.

@cavalos0086 Second tap on already selected button return `null`, because it deselects that option. It's correct behavior, however types are incompatible.

I will create a PR to correct them.

**Comment by PunainenAurinko** [comment]
I think the problem here is the 'correct behavior' of being able to deselect the toggle value. I think we need to have an option of preventing the deselect (and the resulting null value) from happening. I want the tap on the already selected item to do nothing (to not deselect the value). I am switching between views on toggle button taps, and deselecting the value switches to a next view, which is very confusing.

**Comment by maxammann** [comment]
I think null makes sense for the initial case where nothing is selected. If we want to have this state then it should be possible to reach it again.
