### ISSUE TITLE
fix: Menu not showing inside of react-native modal component

### ISSUE THREAD

**Issue by milankyncl** [callstack/react-native-paper#2593]
### Current behaviour

Menu component is not showing inside of `react-native` modal

### Expected behaviour

Menu component to be show even in `react-native` model.

### Code sample

https://snack.expo.io/L5vLMUFpG

### What have you tried

I tried to check if my setup is correct. Outside of modal my menu is working fine, when using inside of `react-native` Modal component, no menu after triggering shows up.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 14.4
| react-native          |  0.63.4
| react-native-paper    | 4.7.1
| node                  | 14.5.0
| npm or yarn           | 1.22.5
| expo sdk              |

**Comment by TOPCODER10192** [comment]
@milankyncl were you able to solve this issue?

**Comment by PunainenAurinko** [comment]
This is issue is still happening to me with RN Paper v. 4.10.0 - Menu is not showing up when triggered from insider a RN modal.

**Comment by fivecar** [comment]
Still happening, with the very latest of everything as of today. [Snack here](https://snack.expo.dev/@fivecar/paper-menu-modal-hang).

The proximate cause is [right here](https://github.com/callstack/react-native-paper/blob/3b3c48105028de7cf1f23d4c0430f47f72415634/src/components/Menu/Menu.tsx#L302) in the code. Basically `Menu.tsx` infinite-spins when `this.menu.measureInWindow` returns zeros, causing it to constantly call `this.show` forever.

Interestingly, when this happens, [`onLayout` here](https://github.com/callstack/react-native-paper/blob/3b3c48105028de7cf1f23d4c0430f47f72415634/src/components/Menu/Menu.tsx#L611) gives the right measurements, despite `measureInWindow` returning zeros. This suggests that using `onLayout` for the window measurements might actually be the right thing, but I don't know the code well enough to be certain that it'll work in all cases.

@lukewalczak : could we re-open this issue? I'm happy to help with a PR if people who understand Menu can review my changes.

**Comment by fivecar** [comment]
@lukewalczak : I've opened #3502, which shows how the infinite loop in `Menu` can be averted by using `onLayout` instead of `measureInWindow`. However, note that this still doesn't show the menu in an RN `Modal` unless you wrap all modal contents within their own `Provider`.

I unfortunately don't understand the `Provider`/`Menu` relationship well enough to know why the `Menu`, even if measured, doesn't show in RN `Modal`s.

**Comment by MathisBarre** [comment]
Have you tried to use the <Portal.Host> container in or around your modal ?

**Comment by fivecar** [comment]
@MathisBarre : Thanks for that suggestion. Yes, using either `<Portal.Host>` or `<Provider>` within an RN `Modal` solves the issue (since `<Provider>` has a `Portal.Host`). Here's a [snack that shows it](https://snack.expo.dev/F90QY5U9U).

My previously-linked PR (#3503) was already merged into main's docs to address this.
