### ISSUE TITLE
[CheckboxAndroid] Why is useNativeDriver flag set to false?

### ISSUE THREAD

**Issue by nachozullo** [callstack/react-native-paper#2631]
I was checking the `CheckboxAndroid` code and I found that `useNativeDriver` is set to false. 

I was wondering if there is an explanation of why is not set to true? 

```
React.useEffect(() => {
    // Do not run animation on very first rendering
    if (isFirstRendering.current) {
      isFirstRendering.current = false;
      return;
    }

    const checked = status === 'checked';

    Animated.sequence([
      Animated.timing(scaleAnim, {
        toValue: 0.85,
        duration: checked ? ANIMATION_DURATION * scale : 0,
        useNativeDriver: false,
      }),
      Animated.timing(scaleAnim, {
        toValue: 1,
        duration: checked
          ? ANIMATION_DURATION * scale
          : ANIMATION_DURATION * scale * 1.75,
        useNativeDriver: false,
      }),
    ]).start();
  }, [status, scaleAnim, scale]);
```

Thanks for the library!

- `react-native`: 0.64.0
- `react-native-paper`: 4.7.2
- `react-native-vector-icons`: 8.1.0

**Comment by lukewalczak** [comment]
Hey @nachozullo, I guess `useNativeDriver` is set to `false` since animated value (`scaleAnim`) is then [used](https://github.com/callstack/react-native-paper/blob/main/src/components/Checkbox/CheckboxAndroid.tsx#L121) on `borderWidth`. Basically, we cannot use native driver on the value which is then used on the different kind of _width_ style.

**Comment by nachozullo** [comment]
Thanks @lukewalczak
