### ISSUE TITLE
DataTable.Row onPress not firing in web

### ISSUE THREAD

**Issue by peh** [callstack/react-native-paper#2634]
### Current behaviour

Clicking on a DataTable.Row does not fire the onPress handler *on web*

### Expected behaviour

DataTable.Row should call the onPress method no matter which environment.

### Code sample

https://snack.expo.io/@bmabsout/datatablerow

### What have you tried

The only workaround I found is defining the onPress handler on each cell which is a bit excessive at times.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | - |
| react-native          | "~0.63.4 |
| react-native-paper    | ^4.7.1. |
| node                  | 15.9.0 |
| npm           | 7.5.3 |
| expo sdk              | ~40.0.0 |
| expo              | ~40.0.0 |

**Comment by peh** [comment]
Bug happens on latest versions as well (see attached snack)

**Comment by lukewalczak** [comment]
Hey @peh, I quickly checked that issue and since it behaves differently between platforms, adding a `pointerEvents` on the `View` which is [wrapping](https://github.com/callstack/react-native-paper/blob/main/src/components/DataTable/DataTableRow.tsx#L65) the children within `DataTableRow` can be the right solution.

That PR should fix the issue: https://github.com/callstack/react-native-paper/pull/2637
