### ISSUE TITLE
Feature request (v5): Bottom app bar

### ISSUE THREAD

**Issue by hbriese** [callstack/react-native-paper#3231]
It would be nice if the bottom app bar from MD3 was added.

https://m3.material.io/components/bottom-app-bar/overview

**Comment by lukewalczak** [comment]
Hey @hbriese, we'll discuss it internally, however you can build `BottomAppbar` based on the `Appbar` component like in the following snack: https://snack.expo.dev/@react-native-paper/bottomappbar.

**Comment by lukewalczak** [comment]
Since it's possible to build `BottomAppbar` using the `Appbar`'s components there is no need to introduce the new component. 
However, we are planning to introduce `safeAreaInsets` _(a similar approach is currently used in BottomNavigation)_ so users can specify the e.g. bottom inset into padding-bottom.
The plan assumes also to extend the example to present how to achieve it, using the new property.
