### ISSUE TITLE
Getting unknown white line over floating label

### ISSUE THREAD

**Issue by mayurgujrathi-eaton** [callstack/react-native-paper#3232]
![TextInput](https://user-images.githubusercontent.com/106810665/176871755-d3c8ca98-a83f-4c06-bf0e-6bad66dd71fb.jpg)

**Comment by mayurgujrathi-eaton** [comment]
react-native: 0.64.0
react-native-paper: 4.11.2
react-native-vector-icons: 8.1.0

**Comment by lukewalczak** [comment]
Could you please check whether bug exists on the latest version? If yes please provide the expo snack or minimal repo.

**Comment by mayurgujrathi-eaton** [comment]
> Could you please check whether bug exists on the latest version? If yes please provide the expo snack or minimal repo.

Tested on latest version also and facing same issue

**Comment by jbcrestot** [comment]
Hello,
I'm pretty sure that this is happening because the device is set to dark mode, and that overrides the background color.

But the background color label is calculated from the TextInput background color which is white and it has a minimum height.

You can reproduce the bug by setting the TextInput background color to black and seeing the color appear behind the label.
