### ISSUE TITLE
Can add custom style fontVariant to TextInput component?

### ISSUE THREAD

**Issue by vylp** [callstack/react-native-paper#3243]
I have a problem with displaying numbers when using a custom font.
![Screen Shot 2022-07-07 at 10 20 04](https://user-images.githubusercontent.com/71864555/177683723-338e7c40-32c0-4940-a046-282b2842601b.png)
Can you please add the option fontVariant to the TextInput style?

**Comment by lukewalczak** [comment]
Hey @vylp, could you please explain what do you mean by the custom font variant?

**Comment by vylp** [comment]
I use rale way font, so by default when i input number it will display like this
<img width="257" alt="Screen Shot 2022-07-20 at 15 36 04" src="https://user-images.githubusercontent.com/71864555/179937108-7891d412-b884-49f6-8638-eb46256574f7.png">
If I set css fontVariant style to ['lining-nums'] 
<img width="177" alt="Screen Shot 2022-07-20 at 15 38 55" src="https://user-images.githubusercontent.com/71864555/179937553-9cf26218-0704-48d9-a3fb-76f766b0db7a.png">

**Comment by lukewalczak** [comment]
I see, will investigate that problem.

**Comment by raajnadar** [comment]
Can you tell me the RN version? I would suggest using the latest RN version in one of the versions this font style issue was solved. I don't remember which version.

**Comment by lukewalczak** [comment]
I think the problem here is the fact that we are [extracting](https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInputFlat.tsx#L83-L87) a couple of text styles properties from the flattened styles, where we are missing `fontVariant `. The rest of the props are passed to the `View` wrapper as a `viewStyle`. Hence, I will add a missing property.

**Comment by lukewalczak** [comment]
Fix released in `4.12.4`
