### ISSUE TITLE
Not able to set custom BottomNavigation backgroundColor with v3 theme.

### ISSUE THREAD

**Issue by DomiR** [callstack/react-native-paper#3290]
As you can see in the reference below, if the v3 theme is used it uses theme surface color no matter what backgroundColor one passes through the `barStyle` prop.

The [NavigationBar Guidelines](https://m3.material.io/components/navigation-bar/guidelines) says:
> The container can have a color fill to provide separation from the content behind it.

https://github.com/callstack/react-native-paper/blob/6afa4fb98c6826c4d6b80db055ef8f21ed07b59a/src/components/BottomNavigation/BottomNavigation.tsx#L602-L605

Also the elevation should probably be adjustable. According to the [NavigationBar Spec](https://m3.material.io/components/navigation-bar/specs#23b08792-3a52-484a-b76c-c37d0b81bb45) it should actually have a default elevation of 2 but it is currently hardcoded to 0:

https://github.com/callstack/react-native-paper/blob/6afa4fb98c6826c4d6b80db055ef8f21ed07b59a/src/components/BottomNavigation/BottomNavigation.tsx#L728

One can barely see it in the example picture:
<img width="387" alt="Bildschirmfoto 2022-08-04 um 12 37 25" src="https://user-images.githubusercontent.com/1834664/182827539-563edda8-4a5f-456b-b3ac-dd183afccb33.png">

**Comment by lukewalczak** [comment]
Hey @DomiR, thanks for your feedback!

If you want to use a custom background color you can always override it by the `theme` prop:

```
      <BottomNavigation
		...
        theme={{ colors: { surface: 'aquamarine' } }}
      />
 ```
 
>  Also the elevation should probably be adjustable. According to the [NavigationBar Spec](https://m3.material.io/components/navigation-bar/specs#23b08792-3a52-484a-b76c-c37d0b81bb45) it should actually have a default elevation of 2 but it is currently hardcoded to 0:

In that case, the `elevation` prop applies background color and shadows, which in terms of `BottomNavigation` is hardcoded to `0`, since there should be no shadow:

<img width="878" alt="Zrzut ekranu 2022-08-4 o 12 55 18" src="https://user-images.githubusercontent.com/22746080/182830576-f07b3f4b-ebee-4131-9ec6-68ae615e038b.png">

However, based on that information you provided and figma kit, the default background color should be `theme.colors.elevation.level2`, which I will correct in the next week.

**Comment by DomiR** [comment]
Hey @lukewalczak. Thanks for looking into this 😊
