### ISSUE TITLE
Website ScrollJacks on Safari. Works fine in Firefox & Chrome.

### ISSUE THREAD

**Issue by deadcoder0904** [callstack/react-native-paper#330]
Regarding https://twitter.com/deadcoder0904/status/986295040673767424

Workaround is to use Firefox & Chrome. Just keeping it here, as on Twitter issues get lost. Feel free to close it if you're only tracking bugs on library :)

**Comment by ferrannp** [comment]
Fixed.

**Comment by satya164** [comment]
Which page are you talking about? We tested on real device and it's fixed.

**Comment by deadcoder0904** [comment]
Safari. It is slow. Wait I'll record GIF.

**Comment by gawrysiak** [comment]
Docusaurus is also used by react-native-ios-kit. Not sure if that's the perfect choice, but it felt a bit better than the paper docs.

**Comment by deadcoder0904** [comment]
Personally I love `react-native-ios-kit` docs more than `react-native-paper` because everything is visible at a glance on the sidebar due to less font size. 

But I wished Docusaurus was an SPA built on top of Gatsby 😂

Also, the scroll jacking issue is there. Not sure about you guys but it happens on my Mac.

**Comment by satya164** [comment]
We generate documentation from comments in the components with custom additions on top of react-docgen and have a decent development workflow with hot reloading for documentation. It's also an SPA and fast to load. Docusaurus is way too limited for us and doesn't make sense to switch to it just because of the styling. We can always change and improve styling of our documentation if we don't like something. I also dislike the styling of Docusauru. It looks way outdated and not-modern. 

> because everything is visible at a glance on the sidebar due to less font size.

I can see 25 items in ios-kit docs sidebar at once and 21 items in paper sidebar on my 15 inch macbook screen, not a big difference. You can't see everything at a glance in Paper because the number of components is way more.

> Also, the scroll jacking issue is there. Not sure about you guys but it happens on my Mac.

The issue reported on twitter was about iPhone, so I only tested on iPhone. Didn't test on Mac. It should be fine on Mac now.

**Comment by gawrysiak** [comment]
I agree with the styling part. Docusaurus has limited possibilities & fixed, a bit outdated looks. The part I don't like so much is the comments in components. Single responsibility for files could stop any unnecessary component file changes. I also can't really imagine placing any longer description/examples in it. Along with the growing possibilities, it could be nice to extends the description/examples with different use cases, just like others do. The component files might feel bloated then.

**Comment by satya164** [comment]
> I don't like so much is the comments in components. Single responsibility for files could stop any unnecessary component file changes. I also can't really imagine placing any longer description/examples in it.

It's hard to keep things in sync when maintaining separate files for docs. Right now lots of things are automatically inferred such as types, static properties, methods etc. Maintaining everything by hand is too much work.

Regarding longer examples, components should themselves be simple enough. We can add examples integrating multiple components and different patterns in guides section which is a better fit.

**Comment by deadcoder0904** [comment]
Wow it works now. @satya164 what did you do to fix it & what was happening❓

I didn't knew you were making docs from comments in files. Yeah I do prefer Docusaurus bcz UX is great if we don't take into consideration it isn't SPA & it doesn't mean yours is bad. I like SPA anyways. 

Now everything works great. Thank you :)

Bdw another question, if we use `ios-kit` for iOS & `paper` for Android, do we have to write a series of `if...else's` to make it work like this -

```js
if (isIOS) {
   return <iOSComponent />
}
return <AndroidComponent />
```

**Comment by gawrysiak** [comment]
I definitely like the props being automatically fetched to the docs. These are just simple one-liners, so no issues with that.

As for the descriptions/examples, I agree the components should be simple, easy to use, but it doesn't mean it's a bad thing to be a bit more verbose on the different use cases. Good and descriptive docs can bring much value to the project, maybe not code-wise, but in terms of presentation, marketing, allowing less skilled programmers to have a quick start with the lib, presenting different possibilities and being a bit more clear on all the why's and when's, bringing in the extra traffic, the same way extra contributors and along with that, new features. Instead of reading the possible props and trying to imagine if that's what we need, the big players tend to describe each type of a component, provide sample image & code. A lot of programmers use the simple copy & paste method with the example they like and adjust on the go (like the button text) instead of trying how things look like with different options.

Some random examples of popular libs describing a simple button: [1](http://getbootstrap.com/docs/4.1/components/buttons/) [2](https://ant.design/components/button/) [3](http://www.material-ui.com/#/components/flat-button) [4](https://docs.nativebase.io/Components.html#button-def-headref) [5](https://blankapp.org/docs/component-button.html) [6](https://shoutem.github.io/docs/ui-toolkit/components/buttons)
The [current docs](https://callstack.github.io/react-native-paper/button.html) seem to be nowhere near that although I really wish you getting there.

**Comment by satya164** [comment]
> what did you do to fix it & what was happening

Probably a bug in safari. This change fixed it: https://github.com/callstack/component-docs/commit/15713e9b50a2697215112ca3f7ae63eaff4f2358

> Yeah I do prefer Docusaurus bcz UX is great if we don't take into consideration it isn't SPA & it doesn't mean yours is bad

I think our DX is better since we have things like hot reloading which docusaurus doesn't.

> Bdw another question, if we use ios-kit for iOS & paper for Android, do we have to write a series of if...else's to make it work like this -

Yeah, we have talked in past to provide a unified lib which uses appropriate libraries according to platform, but we've not arrived at anything yet.

> but it doesn't mean it's a bad thing to be a bit more verbose on the different use cases. Good and descriptive docs can bring much value to the project

Didn't say our docs don't need to be verbose. For example, bottom navigation docs are pretty verbose: https://callstack.github.io/react-native-paper/bottom-navigation.html. They could certainly be improved, but it's all about writing the examples rather than which tool we use to build the documentation.

> A lot of programmers use the simple copy & paste method with the example they like and adjust on the go (like the button text) instead of trying how things look like with different options.

The advantage with the links you shared is that people can see the code and preview at once and then copy it. It's harder in our case since it's React Native. Though probably many of the docs you linked to are also probably auto-generated. I have used tools which generate such detailed examples from CSS files and few templates.

Anyway, moving to docusaurus doesn't solve the problem. We still need to spend a lot of time writing docs and describing different examples. At least, currently there is no need to document all the props and methods manually. When we need detailed examples for complex stuff, right now, we can still use separate markdown files and add it to guides section. And we could eventually add support for moving the examples to markdown files while keeping all other stuff auto-generated. We cannot do such mix and matching with docusaurus.
