### ISSUE TITLE
Snackbar dosent wrap long text to multiline, if children is a view with icon + text

### ISSUE THREAD

**Issue by jimitshah-dp** [callstack/react-native-paper#3360]
**Is your feature request related to a problem? Please describe.**
If Snackbar in V5.0.0-rc.4, is given a view which contains Left aligned icon and right aligned Text, and if the text is long, it doesn't wrap to next line and it overflows out of snackbar

**Describe the solution you'd like**
It should behave same as when we only give text, by default it wraps to next line.

**Describe alternatives you've considered**
If its not wrapped in a view, the icon and text renders, but the alignment are off, as it does not adhere to any margin props between icon and text

**Additional context**
Example Code:
` <Snackbar>
      <View
        style={{
              flexDirection: 'row',
              alignItems: 'center',
        }}
      >
        <Icon
          name={iconToUse}
          size={20}
          style={[styles.mr14, containerClasses]}
        />
        <Text>Error Message which is veryyyy longggggggg</Text>
      </View>
    </Snackbar>`

<img width="403" alt="Screenshot 2022-09-07 at 12 48 31 AM" src="https://user-images.githubusercontent.com/82024000/188720502-3d9d8353-24cb-4552-a0c7-b649024c0f29.png">

**Comment by jimitshah-dp** [comment]
react-native: "0.68.2",
react-native-paper: "5.0.0-rc.4",
react-native-vector-icons: : "9.2.0",

**Comment by lukewalczak** [comment]
Hey @jimitshah-dp, could you please provide the [snack]([snack.expo.dev](https://snack.expo.dev/)) presenting the issue?

**Comment by jimitshah-dp** [comment]
@lukewalczak here is the demo, try on android https://snack.expo.dev/EYNfxoKLd

Let me know if you need anything else

**Comment by lukewalczak** [comment]
Material Design documentation indicates that containing an icon/image in the `Snackbar` is the wrong approach:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/22746080/189604443-787c212f-16f0-4e55-a6bd-9ab36cff3b5c.png">

Through analysis of the `Snackbar` component code, I think it was crafted to accept only _string_ or `Text` component, that's why placing the `View` inside the `Snackbar`may not work correctly.

We will internally discuss it and it will be considered in the nearest future.
