### ISSUE TITLE
Use Pressable component within TouchableRipple

### ISSUE THREAD

**Issue by lukewalczak** [callstack/react-native-paper#3396]
**Is your feature request related to a problem? Please describe.**
According to the feature request title, we would like to replace the currently used `Touchables` in favour of `Pressable` within `TouchableRipple` component.

**Describe the solution you'd like**
Replace `Touchables` with `Pressable` within `TouchableRipple`

**Comment by szymonrybczak** [comment]
I can do it 😀 Today I will create pull request for that.

**Comment by szymonrybczak** [comment]
hey @lukewalczak I've stuck on the problem, and I've a question to make sure that I'm right. If we change everything to `<Pressable />` we can't use `delayPressIn`, but there is `unstable_pressDelay`, and to use it I need to update `@types/react-native`, because current version `0.66.1` doesn't contain this prop, should I update types library to `0.68.2` and change everywhere where `delayPressIn` was used to `unstable_pressDelay`?

**Comment by lukewalczak** [comment]
Hey @szymonrybczak let's consider removing usages of that prop from components at all.

**Comment by lukewalczak** [comment]
Closed via https://github.com/callstack/react-native-paper/pull/3400
