### ISSUE TITLE
Q: Where can i find changelog fot this project?

### ISSUE THREAD

**Issue by syedabuthahirm** [callstack/react-native-paper#343]
Where can I find the changelog for this repo? As of now, I am using 1.2.4 but I would like to know about the current version pros.

**Comment by gawrysiak** [comment]
It seems like the changelog is still [in progress](https://github.com/callstack/react-native-paper/issues/275), but it should be fairly easy to simply browse the [commit messages](https://github.com/callstack/react-native-paper/commits/master) to look into the updates. It should be pretty straightforward to update since I don't really remember any breaking changes.

**Comment by satya164** [comment]
Yeah, we don't have any breaking changes. We follow semver, so we'll do a major release if we introduce breaking changes.

**Comment by syedabuthahirm** [comment]
Sure. Thanks, I updated my app with a new version.
