### ISSUE TITLE
Text within button is truncated by default if character length of text is equal to 10

### ISSUE THREAD

**Issue by goofygoobers** [callstack/react-native-paper#3472]
### Current behaviour

This issue is specifically found when emulating an Samsung S22 device. 
When the text is exactly 10 characters long, it is automatically truncated. 

### Expected behaviour

The expected behaviour is for the text in the button to not be truncated. 

### How to reproduce?

1. Create a samsung galaxy s22 device on android studio with this skin (Galaxy 22) https://developer.samsung.com/galaxy-emulator-skin
2. Create a button with a text component within it.
3. Within the text component, add a single word with exactly 10 characters.

https://snack.expo.dev/9wx1ycteed

### Preview

As shown below, the "Statements" button on the second row is truncated. 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/63584829/202070572-a0a1ad92-487b-4693-b1c8-5f9b588c4a65.png">
This is not a problem on IOS simulator as shown below. 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/63584829/202070688-f71ac917-9f7e-4089-89dd-d42f8525446a.png">

### What have you tried so far?

1. I've checked on IOS simulator, it doesn't seem to be a problem there. 
2. This is also not a problem on Pixel android devices i've emulated on. 

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.4
| android                        | 13
| react-native                |"0.69.3",
| react-native-paper    | 5.0.0-rc.6
| node                            | v18.7.0
| npm                             | 8.15.0
| expo sdk                     | Not using

**Comment by lukewalczak** [comment]
Hey @goofygoobers, does the issue exists on the stable v5 e.g. `5.1.0`?

**Comment by sapjax** [comment]
> Hey @goofygoobers, does the issue exists on the stable v5 e.g. `5.1.0`?

`5.1.2` still has this issue.

**Comment by lukewalczak** [comment]
> 5.1.2 still has this issue.
the problem exists on my actual android device, but it does not exist on the Android simulator.

Could you please try to investigate the issue once you're able to reproduce the problem?

**Comment by sapjax** [comment]
> > 5.1.2 still has this issue.
> > the problem exists on my actual android device, but it does not exist on the Android simulator.
> 
> Could you please try to investigate the issue once you're able to reproduce the problem?

I think it's an issue with React Native itself, currently, I found two ways to get around this problem:
1. add a space to the end of the button text, like `<Button>Connect </Button>`
2. set `uppercase` to the button, `<Button uppercase>Connect</Button>`

**Comment by lukewalczak** [comment]
Hey @sapjax, thanks for your input! Were you able to observe the same issue with the regular react-native's `Text` component, when `letterSpacing` is set to `0.1`? What device/emulator are you using?

**Comment by lukewalczak** [comment]
Closing the issue, since the problem is related to the specific device and its internal display settings, so it's hard to apply the fix, which will fit in all the users cases. 

The mentioned [solution](https://github.com/callstack/react-native-paper/issues/3472#issuecomment-1376723484) can be applied manually to the projects, which are affected by that problem.

**Comment by surbhidavara99** [comment]
I am having the same issue in iOS if I am testing in the simulator it's not getting ellipsis but in real devices, the text is cutting. sharing screenshot here. 


![iPhone](https://github.com/callstack/react-native-paper/assets/74037332/fc1754e4-2413-4a6d-a302-b645d77e9842)

**Comment by surbhidavara99** [comment]
I am having the same issue in iOS if I am testing in the simulator it's not getting ellipsis but in real devices, the text is cutting. sharing screenshot here.

Device info: iPhone SE(15.7.8) 

![iPhone](https://github.com/callstack/react-native-paper/assets/74037332/ad521117-447d-4cef-bc34-1c821b3b0d95)

**Comment by rickymohk** [comment]
Also having this issue with text length of every multiple of 5, when system font size is set to "Default".

**Comment by ClaudiaSkyeB** [comment]
I'm also having this issue with text length of every multiple of 5, when system font size is set to "Default". So far I've noticed it on the Mobicell Legend Pro Lte on Android 11 and with an emulated Galaxy Nexus API 30 device with a 720p 4.65 display with Android 11. The only way I was able to fix it so far was to add spaces to increase the text length. The letterspacing wasn't the problem in my case. Would be very cool if we can get a fix for it.

**Comment by rayoogmy** [comment]
I am seeing this too. This is on react-native-paper 5.13.1.

**Comment by fwielstra** [comment]
This is still an issue, I just triggered it with the following properties:

font family: open sans
font weight: 700
line height: 24
font size: 16
letter spacing: 0.2
Text: "Secondary processing"

Changing the text so that the length (in pixels) changes, e.g. adding a letter or replacing a wider character with an "i" makes the bug not appear.

I've fixed it by adding `0.001` to the letter spacing. I presume the cause is a math bug or floating point rounding error somewhere.

**Comment by ChronSyn** [comment]
Adding `minWidth: "100%"` as a `labelStyle` property resolved this for my specific situation, but that won't guarantee to resolve it for every situation.

**Comment by JenqaaaBY** [comment]
I’ve run into this problem as well. In the project initialization file, make sure you load the custom fonts first and only then render the rest of the component tree (e.g., return null or a loader until useFonts resolves).
  The issue happens because Android measures the layout on the first render with the system font; if the custom font arrives afterwards, the layout never gets recalculated, so the text gets truncated. During a hot reload the font is already cached, so the problem seems to disappear.

**Comment by abettermap** [comment]
The [accepted answer](https://github.com/callstack/react-native-paper/issues/3472#issuecomment-1376723484) only worked sporadically for me. I ended up just adding a trailing space `{ }` in the JSX when I encountered the problem. Not the best solution, but it did work.
