### ISSUE TITLE
Support italics in custom fonts.

### ISSUE THREAD

**Issue by jennifersalas** [callstack/react-native-paper#3499]
**Is your feature request related to a problem? Please describe.**
One issue I'm having is setting custom fonts with italics. There isn't any support for custom fonts with italics when setting the theme. Further if you do set fonts in the custom theme, the Text component will no longer actually italicize the text. This has resulted in always have to create our own custom Text components.

**Describe the solution you'd like**
Add support for italicizing with custom fonts.

**Describe alternatives you've considered**
Creating our own custom components that wrap around the Text component to overwrite the fonts. The issue is still persistent in external library components that use Paper's Text component.

**Comment by lukewalczak** [comment]
Hey @jennifersalas, could you please provide more details about your issue, maybe you can provide the snack. Please also provide some details like Paper version or platform which it affects.

**Comment by Streudal** [comment]
I may be able to shed some light on this since this happened to me today. Problem for me seems to only effect iOS.

I am using Typescript with React Native but had no need to create customVariants via the fontConfig. Only the need to change the default `fontFamily` to the [Inter](https://fonts.google.com/specimen/Inter?query=inter) font.

react-native: 0.71.3
"react-native-paper": "5.3.1"

I added in a custom font (Inter) and just wanted the default 'fontFamily' to be that font from following [these](https://callstack.github.io/react-native-paper/docs/guides/fonts/#material-design-3:~:text=However%2C%20if%20you%20just%20want%20to%20override%20any%20font%20property%20e.g.%20fontFamily%20or%20letterSpacing%20for%20all%20variants%2C%20you%20can%20pass%20the%20fontConfig%20as%20a%20config%20into%20the%20params%20object%20without%20specifying%20variant%20name) instructions in the docs.

This all worked great until I tried to change the `fontStyle` property to 'italic' and it didn't take effect on iOS. It worked fine on Android.

Here is what I was getting:

**iOS**
![image](https://user-images.githubusercontent.com/35472790/226672515-fb20ba3f-ad79-4bc6-b160-5b88b4f88908.png)

**Android**
![image](https://user-images.githubusercontent.com/35472790/226672656-d2ef7f7f-40ba-48f5-8576-b3c4129f26c8.png)

You can clearly see the iOS text is not italicized but the Android text is.

Also, I think what was mentioned by @jennifersalas is that there is also no configuration to set the `fontStyle` in the fontConfig but everything else you can related to fonts.

Hopefully this helps!
