### ISSUE TITLE
IconButton cannot be elevated

### ISSUE THREAD

**Issue by rKatex** [callstack/react-native-paper#3564]
https://github.com/callstack/react-native-paper/blob/fe16b9f425bff63dd647a7de6cbae714811b51bf/src/components/IconButton/IconButton.tsx#L172

Hello,

I'm trying to give an IconButton (v3) some elevation on android (via styling), but sadly that is not possible because elevation is always hardcoded to be 0 for IconButtons.

While debugging, I was wondering why the container of the IconButton needs to be a Surface, when the elevation is disable anyway. I removed the mentioned line above and replaced the Surface with View and it worked like I expected it to work.

```
...
<View
  ref={ref}
  style={
    [
      {
        backgroundColor,
        width: buttonSize,
        height: buttonSize,
      },
      styles.container,
      borderStyles,
      !isV3 && disabled && styles.disabled,
      style,
    ] as StyleProp<ViewStyle>
  }
>
...
```

Is it generally wrong to give IconButtons elevation or would the suggested code be applicable?

**Comment by lukewalczak** [comment]
> Is it generally wrong to give IconButtons elevation or would the suggested code be applicable?

Material Design 3 doesn't indicate there can be an elevated `IconButton` that's why there is no support for that:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/22746080/210099011-68e0dd73-01e9-4f17-82d5-19eeca9d2745.png">

> While debugging, I was wondering why the container of the IconButton needs to be a Surface

I guess supporting elevation was kinda possible in the previous version, that's why that component was based on the `Surface` component. For the purpose of adjusting `IconButton` to the latest MD guidelines, we kept the Surface component, however with disabled _elevation_ (set to 0).
