### ISSUE TITLE
Unknown margin on top of TextInput

### ISSUE THREAD

**Issue by somasekharkakarla** [callstack/react-native-paper#3669]
### Current behaviour
The unknown margin on top

### Expected behaviour
There should be no margin

### How to reproduce?
```
 <View style={{flex:1, borderWidth:2, borderRadius:8, borderColor:'grey', justifyContent:'center'}}>
        <RNTextInput mode={'outlined'} outlineStyle={{borderRadius:0, borderWidth:0, backgroundColor:'red', margin:0, padding:0,flex:1, alignSelf:'center'}}/>
      </View>
```

### Preview
<img width="392" alt="Screenshot 2023-02-10 at 4 44 46 PM" src="https://user-images.githubusercontent.com/65530762/218095826-a24614a3-1c61-420a-92c9-51705223d911.png">

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.70.5
| react-native-paper    | 5.0.0-rc.9

**Comment by lukewalczak** [comment]
Please try to install the latest stable version `5.2.0` and if the issue still occurs please attach the [snack](https://snack.expo.dev/)

**Comment by somasekharkakarla** [comment]
Hi @lukewalczak,

As you suggested I upgraded my react-native-paper lib to v5.2.0 but still the issue exists. Here is the snack link https://snack.expo.dev/qiAeK7t3h

**Comment by lukewalczak** [comment]
Thanks, we'll check the issue.

**Comment by tjaniczek** [comment]
Hi @somasekharkakarla !
<img width="403" alt="image" src="https://user-images.githubusercontent.com/7429558/220075158-4febee8d-1fd7-4644-a33a-8cf4b06aa636.png">

Please note this padding is needed so that the floating label won't get obscured while input field is focused. Input fields without the label are not recommended by Material due to accessibility issues: https://m3.material.io/components/text-fields/guidelines#d65e62c9-97a4-437c-a099-23acea26e68a
