### ISSUE TITLE
Material You <Switch> component design

### ISSUE THREAD

**Issue by indyteo** [callstack/react-native-paper#3689]
**Is your feature request related to a problem? Please describe.**
I searched the issues for a mention about the `<Switch>` component being migrated to Material You (M3) but I didn't found any. Currently, the design is the one from M2 (see [here](https://m3.material.io/components/switch/overview#4b59cb6e-4d8f-47ed-8aa7-4d4576f1c099) for the difference).

**Describe the solution you'd like**
I would like to be able to use the [new switch design](https://m3.material.io/components/switch/overview) inside React Native Paper.

**Describe alternatives you've considered**
I know this is a minor issue and everything works great now, it's just the only component I saw that uses the old style, so I'm confused whether this is intentional or not. The [docs](https://callstack.github.io/react-native-paper/switch.html) does not state anything particular about this...

**Additional context**
You can find all the specs (including screenshots) about the new design of the switch [here](https://m3.material.io/components/switch/specs).
I'm sorry if this was already discussed somewhere else, I did not find it.

**Comment by lukewalczak** [comment]
Hey @indyteo, our goal for `Switch` component is to use the native component from the `react-native`, however, it still has the old design as you've noticed.
Actually, we considered crafting the custom component, but it's more work to build that one and make sure that e.g. accessibility works properly across all platforms – with the native component we have the guarantee of the built-in a11y support.
In my opinion, it's an issue with React Native itself not using the correct design according to the system and I lean towards it needs to be fixed on React Native side since we are importing the switch from there.

**Comment by indyteo** [comment]
Hello, I understand your opinion, I didn't know that the Material Design system was implemented by React Native itself, I always thought it was external libs (such as this one) that made a "bridge" between React Native and the designed components.
Or maybe you just can't override the default styles for this component? In that case OK I understand there's something to be done by React Native itself...
Thank you for your reply, and as I said above, this really is a minor issue and I think most of the users don't mind having one design or another, I was more a question about why it has not been done yet, and now I have the answer :)
