### ISSUE TITLE
Dialog TextInput Cursor Flickering

### ISSUE THREAD

**Issue by tingan** [callstack/react-native-paper#3831]
### Current behaviour
use react native paper to create a dialog
     <Dialog visible={visible} onDismiss={hideDialog} style={styles.dialog}>
                <Dialog.Content scrollEnabled={false}>
                    <TextInput
                        label=""
                        multiline={true}
                        mode={'outlined'}
                        value={importText}
                        onChangeText={text => handleTextChange(text)}
                        style={styles.input}
                    />
                </Dialog.Content>
            </Dialog>

### Expected behaviour
user should be able to type in the dialog's text input, but it's not possible as it flicker. see here: 

### How to reproduce?
create a dialog as above code snippet and try to type in text input.

### Preview
[](https://stackoverflow.com/questions/64921365/react-native-paper-textinput-in-modal-cursor-flashes-backwards-after-a-characte)

### What have you tried so far?
 I have to change to value={importText} to defaultValue={importText}, but it's not good solution.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 11
| android                        | x
| react-native                | 0.71.6
| react-native-paper    | 5.7.0
| node                            | 16.17.0
| npm                             | 8.15.0
| yarn                             | 3.5.0
| expo sdk                     | 48.0.7

**Comment by lukewalczak** [comment]
Hey @tingan, please provide the expo snack, presenting the issue which you are facing.

**Comment by tingan** [comment]
https://stackoverflow.com/questions/64921365/react-native-paper-textinput-in-modal-cursor-flashes-backwards-after-a-characte

**Comment by lukewalczak** [comment]
Hey @tingan, as you may notice in the thread from the stackoverflow attached above the issue comes from `react-native` - there is a known issue with inputs within portals in general, not only in the paper library. 

Within the other issue you can find the [workaround](https://github.com/callstack/react-native-paper/issues/1668#issuecomment-586005762).

Please also check that [approach](https://github.com/jeremybarbet/react-native-portalize/issues/6#issuecomment-761907191) which can be helpful.

Also please take a look on the [snack](https://snack.expo.dev/@react-native-paper/input-with-portal)

**Comment by markendy** [comment]
Progress never stands still, so perhaps the new solution described in this question will help you! https://stackoverflow.com/questions/79253174
