### ISSUE TITLE
Upgrading to react-native-paper 5.9.1 changed my react-navigation/material-bottom-tabs

### ISSUE THREAD

**Issue by dheeraj539** [callstack/react-native-paper#4005]
How can I customize the behavior of material-bottom-tabs to achieve the desired outcome displayed below?

![Required](https://github.com/callstack/react-native-paper/assets/25552328/e19e6280-8b6a-49aa-946a-e9375eb14cd5)

After upgrading my react-native-paper to 5.9.1 the UI of material-bottom-tabs completely changed.
Before upgrading to v5:

![Required](https://github.com/callstack/react-native-paper/assets/25552328/2a168c9b-d173-4a4e-a97d-0c42e0c97914)

After upgrading to v5:

![Existing](https://github.com/callstack/react-native-paper/assets/25552328/7ad0706b-f6bc-45f1-a42b-2daa7c47334c)

**Comment by lukewalczak** [comment]
> After upgrading my react-native-paper to 5.9.1 the UI of material-bottom-tabs completely changed.

Did you follow migration guide to v5? If you want to keep old design from v4, there is a need to specify `version` property in the theme, please check the section related to that: https://callstack.github.io/react-native-paper/docs/guides/migration-guide-to-5.0#versioning

**Comment by dheeraj539** [comment]
> > After upgrading my react-native-paper to 5.9.1 the UI of material-bottom-tabs completely changed.
> 
> Did you follow migration guide to v5? If you want to keep old design from v4, there is a need to specify `version` property in the theme, please check the section related to that: https://callstack.github.io/react-native-paper/docs/guides/migration-guide-to-5.0#versioning

Changing the version is the first thing that I tired, but it didn't work.
FYI, I am using the react-navigation/material-bottom-tabs package

**Comment by lukewalczak** [comment]
In order to have an older design in `react-navigation/material-bottom-tabs` after `react-native-paper` upgrade, you need to wrap your app root in `PaperProvider` from `react-native-paper` and pass there the theme for MD2 – `MD2LightTheme`, `MD2DarkTheme` or your custom theme with `version: 2`.

Please check the snack below: 
https://snack.expo.dev/@react-native-paper/material-bottom-tabs-navigator-%7C-react-navigation

If you still have a problem, please create your own snack and I will try to help you 🙌🏽

**Comment by dheeraj539** [comment]
Thanks for the snack !!! That resolved my issue. I was using the older version of material-bottom-tabs before, because of which I wasn't able to switch to MD version 2.
