### ISSUE TITLE
Edge to edge android app

### ISSUE THREAD

**Issue by AminAhmadyDeveloper** [callstack/react-native-paper#4090]
Hi on android devices appbar color goes under statusbar and it looks perfect but why app shouldn't do the same thing for navigation bar, problem is navigation bar remains unstyled

Solution is make android app to be edge to edge for device even drawer like it goes under statusbar.

Additionally this is how flutter handles this future:
https://api.flutter.dev/flutter/services/SystemChrome-class.html

**Comment by lukewalczak** [comment]
Hey @AminAhmadyDeveloper, missing edge-to-edge support is not related to the Paper library. By default, even the react native template doesn’t even have a translucent navigation bar. 

In order to make your app edge-to-edge on Android device you can use [Expo Navigation Bar](https://docs.expo.dev/versions/latest/sdk/navigation-bar/) library and for instance use method `setBackgroundColorAsync` to change the navigation bar's background color.
