### ISSUE TITLE
Button Size Feature

### ISSUE THREAD

**Issue by Lev-Shapiro** [callstack/react-native-paper#4116]
Probably that would be a good idea to add default sizes for buttons ( "small" | "normal" | "large" ) as it is made in MUI ( React library ).

**Comment by Lev-Shapiro** [comment]
I'll do PR for this tomorrow

**Comment by lukewalczak** [comment]
Hi @Lev-Shapiro, appreciate your feature request and willingness to contribute. However, kindly hold off on the implementation for now. I'd like to take some time to fully understand your suggestion and discuss it with the team before making a decision on whether to introduce it into the library. Thanks for your patience!

**Comment by lukewalczak** [comment]
Since there is an option to use styles to customize the `Button`'s size, there is no need to introduce a predefined size via additional prop. 
In terms of the library component, the source of truth is Material Design guidelines, which doesn't indicate that property in specs, hence rejecting that feature request.
