### ISSUE TITLE
Tooltip on web is not working properly since version `5.7.1`.

### ISSUE THREAD

**Issue by mathias-berg** [callstack/react-native-paper#4139]
### Current behaviour
I'm using version `5.7.0` and all works fine. When I hover over something, the tooltip shows, and then it goes away when I stop hovering. It also works with the delays.

Since version `5.7.1` my tooltips just behave very strange. Even if I stop hovering, it still shows after the delay. So I keep up ending with multiple tooltips showing.

### Expected behaviour
To work as it does in `5.7.0`. When hover it shows, when not hovering, it goes away.

### How to reproduce?
Easy, just try to hover the icons in this Snack.
https://snack.expo.dev/@fyranollfyra/tooltip-not-working

If I remove the `onPress` on the `IconButton` everything works as expected.

### Preview
<img width="419" alt="image" src="https://github.com/callstack/react-native-paper/assets/26097801/6fa1c275-cbea-4018-b4c0-ff118f8fa0cf">

### What have you tried so far?
Just tried different versions and found

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.71.3
| react-native-paper    | 5.7.1 (5.7.0)
| node                            | 18.15.0
| yarn                             | 1.22.19
| expo sdk                     | 48.0.20

**Comment by mathias-berg** [comment]
It seems to be this commit that did the changes.
[a7cc33e5c577493cecdf2caa6ba261f6b5d21288](https://github.com/callstack/react-native-paper/commit/a7cc33e5c577493cecdf2caa6ba261f6b5d21288)

**Comment by artus9033** [comment]
Due to the fact that `Tooltip` in react-native-web passes down its `webPressProps` down both to a `Pressable` that wraps the child and to the child component itself:
https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/components/Tooltip/Tooltip.tsx#L207-L216
it is possible for a race condition that breaks the expected behaviour to occur, given three conditions are fulfilled:
- the `Tooltip`'s `children` prop is a component that finally passes its `onHoverIn` prop down to a `Pressable`, which is the case in @mathias-berg's situation, or performs equivalent behaviour in a different way
- the `Tooltip` is passed a reasonably large `enterTouchDelay` value (`1800`ms taken from this issue is enough for the bug to be reproducible)
- at the same time `leaveTouchDelay` is reasonably smaller than the `enterTouchDelay` (which in the reported case is the default value of `500`ms, which is suitable for `enterTouchDelay={1800}`)

Consider a situation when `handleTouchStart` is being called from `Tooltip`'s `Pressable` wrapper sets a "show tooltip" timer :
https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/components/Tooltip/Tooltip.tsx#L127-L132
and is immediately overwritten by a consecutive call to this callback from the child itself, which is passed that same callback (the passing of that prop is a desired behaviour, otherwise the child component would be ripped of a way to handle this event).
Now it is easy to imagine that with a sufficiently long `enterTouchDelay` and sufficiently smaller `leaveTouchDelay` it is possible that a first delayed "show tooltip" timeout that id of was overwritten by the second invocation, would not be cleared in `handleTouchEnd` (which would clear only the second, newest, timeout) and thus "show tooltip" would fire at the very last, not being reversed at all within this interaction.

<img alt="RNPaper 4139 reproduction" src="https://github.com/callstack/react-native-paper/assets/10586109/b28f0984-a225-492c-897c-5271fec36430" width="50%">

A fix for that would be to make refs hold arrays of timeout IDs instead of a single ID and clear all of them each time such a clearing is performed now. This is the result with additional logging of the IDs of timeouts set & cleared:

<img alt="RNPaper 4139 fixed" src="https://github.com/callstack/react-native-paper/assets/10586109/101f8630-94ca-4d73-bf1c-92e1443714ae">

**Comment by kimchouard** [comment]
AMAZING ! This was very painful. I was about to open a PR to fix this, thanks @artus9033 for working on it ahead of me 😉🙏
