### ISSUE TITLE
Icons do not match the corresponding name

### ISSUE THREAD

**Issue by rybaier** [callstack/react-native-paper#4281]
### Current behaviour

icons do not match the description. see screenshot for example

<img width="516" alt="Screenshot 2024-01-17 at 12 09 39 PM" src="https://github.com/callstack/react-native-paper/assets/95250095/b0f45c69-a5c9-4c51-9f79-179bdfc90eea">

### Expected behaviour

expected it to be a checkmark and a cancel circle

### How to reproduce?

https://github.com/rybaier/TODOAPP

### What have you tried so far?

changing the icon names. none of them match up
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 33
| react-native                | 0.73.2
| react-native-paper    | 5.12.1
| node                            | 21.5.0
| npm or yarn                | 10.2.4

**Comment by rybaier** [comment]
here's the repo @lukewalczak 
https://github.com/rybaier/TODOAPP

**Comment by NazmaD** [comment]
@rybaier  I encountered a similar issue, and by incorporating the following line into the app/build.gradle and subsequently reinstalling the app worked for me.

`apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle")`

**Comment by lukewalczak** [comment]
Hey @rybaier, I couldn't find a `react-native-vector-icons` to be installed in your project, which is required step in order to to have added `MaterialCommunityIcons`, because some components use those internally. 

Please follow the [getting started](https://callstack.github.io/react-native-paper/docs/guides/getting-started), more specifically, the paragraph related to the icons installation.

At the moment I'm closing the issue.

**Comment by rybaier** [comment]
Hey @lukewalczak I had it installed originally and removed it while trying to debug. Per your recommendations I reinstalled react-native-vector-icons. At that point, I am still seeing the incorrect icons.  After applying the line that @NazmaD  suggested to the app/build.gradle file it ran correctly with the corresponding icons. 

Thank you both!
