### ISSUE TITLE
Tootip import  module error

### ISSUE THREAD

**Issue by ayobamiseun** [callstack/react-native-paper#4468]
### Current behaviour

when I imported Tootip from **react-native-paper** `import { ProgressBar, Provider, Portal, Tooltip } from 'react-native-paper';`  I got the error _Module '"react-native-paper"' has no exported member 'Tooltip'._

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.74.3
| react-native-paper    | 4.12.8
| node                            | 18
| npm or yarn                | x.x.x
| expo sdk                     | 51.0.21

**Comment by kamilkedzierski** [comment]
Hey @ayobamiseun ! 

It looks like you're encountering this issue because version `4.12.8` of `react-native-paper` does not include the `Tooltip` component (see the screenshot below). To use the `Tooltip` component, you'll need to update to the recent version of the library.

![image](https://github.com/user-attachments/assets/a2d2a0ac-c890-4be0-9e7f-b5702d527c80)

**Comment by ayobamiseun** [comment]
@kamilkedzierski  bless up this give me an head up.

**Comment by kamilkedzierski** [comment]
@ayobamiseun Hey! Just checking in—can we close this issue, or do you have any questions? 😊
