### ISSUE TITLE
Default /global props for Text, TextInput, etc

### ISSUE THREAD

**Issue by peacechen** [callstack/react-native-paper#462]
### Current behaviour

Component-specific props can't be set in the theme.  Only a few styles such as font family, color etc may be globally set.

RN used to allow setting global props in this fashion:
```
Text.defaultProps.allowFontScaling = false;
Text.defaultProps.fontFamily = 'Helvetica';
```

Unfortunately that was removed in RN 0.56.

### Expected behaviour

Add global props for the Paper components that apply to all instances, much like the color properties.   See code example below.

### Code sample

A proposal for a `textProps` object which is passed down to the Text component
```
const theme = {
  ...DefaultTheme,

  // Example: prevent OS-level font scaling
  textProps: {
    allowFontScaling: false
  }
};
```

The change to Paper's Text component would be straight-forward.
https://github.com/callstack/react-native-paper/blob/master/src/components/Typography/Text.js#L35
```
    return (
      <NativeText
        { ...(theme.textProps || {}), ...this.props }   <---PASSED DOWN HERE
        ref={c => {
          this._root = c;
        }}
        style={[
          { fontFamily: theme.fonts.regular, color: theme.colors.text },
          style,
        ]}
      />
    );
```
 
Would you accept a PR for this?

### What have you tried

Theme doesn't pass down arbitrary props.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios and android
| react-native          | 0.56
| react-native-paper    |  1.11.0
| node                  | 9
| npm or yarn           | 4.5

**Comment by satya164** [comment]
I don't think we want to allow passing arbitrary props from theme object. The reasons are the same as to why we avoid global CSS:

- Global properties break encapsualtion. You can no longer look at a component's usage and know how it is going to look.
  + Since theme providers can also be nested, you'll need to look at every parent to determine where the props are coming from
  + Changing some property in the theme can break totally unrelated component which you might not notice. It increases maintenance cost.
- In the current theming implementation, themes are merged deeply. This can easily break props which accept objects.
- It's extra work to write such components, for every component, we'll also need to remember to add it's props to the theme object, plus write extra logic to merge global props with local props, which is also easy to forget. This happens automatically for themes, but I don't see an automatic way to do this for props.
- It's hard to statically type.
- It doesn't make sense for a lot of props. For example, setting a `label` prop globally for buttons don't make much sense. Very few props such as `allowFontScaling` actually make sense to set globally, though I'm against setting it to false globally since it hurts readability for visually impaired users.

The first point is also an issue in themes. But theming is a very common requirement and the benefits outweigh the tread-offs. This is also why we have very few properties in the theme which are very generic, and mostly just fonts and colors.

The easiest way to achieve what you want is to just create a custom component with preappllied props and use it everywhere as we outlined in the docs https://callstack.github.io/react-native-paper/theming.html. It's explicit and easier to maintain in the long run.

You could also use the `withTheme` HOC from Paper to allow customizing these things globally for your custom component. Though I'd not recommend that.

**Comment by peacechen** [comment]
This is obviously a difference of opinion, but "global" props aren't such a bad thing.  And my proposal isn't actually global in the sense of applying props to every single component.  They're very targeted, for example `textProps` applies specifically to the Text component.  Are you concerned that the components which use Text may be affected?  The `textProps` should continue to automatically apply in that case.

In the cases where I need props to truly apply to all components of a specific type (e.g. fontFamily for Text), creating a HOC adds another layer of complexity and maintenance.

This debate really centers around which perspective is taken:  make it easier for app developers, or make it easier the the library (react-native-paper).  I understand the desire to avoid complexity in RNP, however this means that every app developer needs to take on the work and implement it separately.  It's duplicated work that makes more sense being handled in the library.
