### ISSUE TITLE
Image lists

### ISSUE THREAD

**Issue by alvaromb** [callstack/react-native-paper#610]
https://material.io/design/components/image-lists.html

**Comment by alvaromb** [comment]
@ferrannp @satya164 we'll be available to work on this next week, would you like us to add this component to the library?

**Comment by alvaromb** [comment]
I would start first by this https://material.io/design/components/image-lists.html#anatomy and then the containers https://material.io/design/components/image-lists.html#specs

**Comment by satya164** [comment]
I think what we want is a `GridView` component. The `GridView` component could have any kind of children, including images. We had one before: https://github.com/callstack/react-native-paper/pull/73, but we removed it because it didn't work well in many scenarios: https://github.com/callstack/react-native-paper/issues/246

**Comment by alvaromb** [comment]
What about the image list item? They seem pretty standarized in Material guidelines (see [Anatomy](https://material.io/design/components/image-lists.html#anatomy)).

**Comment by satya164** [comment]
Yea, we could have a separate component for that which you can render in the `GridView`.
