### ISSUE TITLE
TextInput Outlined mode: (Focused)  

### ISSUE THREAD

**Issue by sritharanpalani** [callstack/react-native-paper#656]
### Current behaviour
Text input appeared when mode=outlined is violet colour border

### Expected behaviour
 i want to change the violet to my custom colour ,what is the way to do it ,i look into the document but i don't find any props regarding that

**Comment by saharjedidi** [comment]
<TextInput 
  label='password '
        mode='outlined'
        secureTextEntry='true'
        underlineColorAndroid={'rgba(0,0,0,0)'}
        style={this.getStyle().TextInp} 
         text='white'
        direction ='rtl'
        value={this.state.text}
        editable= 'true'
        onChangeText={password => this.setState({ password })}
        underlineColor='transparent'
        editable= 'true'
       
        theme={{ colors: { placeholder: 'white', text: 'white', primary: 'white',underlineColor:'transparent',background : '#003489'}}}
        >

**Comment by Trancever** [comment]
@sritharanpalani  You can change `primaryColor` in your theme, or as @saharjedidi suggested, pass theme prop to component.

**Comment by ajitdas123** [comment]
@Trancever Is there anyway way, that we can disable the bottom border for the flat input, or maybe we can give color to label and border individually?

**Comment by FaelSant** [comment]
@ajitdas123  i want to know too.

**Comment by lylest** [comment]
i want to know to

**Comment by daviddunnington** [comment]
My solution for this was to use the placeholder prop instead of the label, you can then use the placeholder color prop to give it a different color to the border/placeholder, the only caveat is that you don't get the floating label when you click inside the input which was fine for my use case as it was a search input and not required. Would be great if you could stye the label and border individually.

My final code looked like this 
`<TextInput
            mode="outlined"
            style={styles.inputContainerStyle}
            value={searchTerm}
            onChangeText={(text) => handleChange(text)}
            autoCapitalize="none"
            autoCorrect={false}
            placeholderTextColor={'black'}
            placeholder="Search"
            color={lightGrey}
            theme={{
                colors: {
                    placeholder: neutral100,
                    label: 'red',
                    border: 'red',
                },
                roundness: 10,
            }}
            left={
                <TextInput.Icon
                    name={() => <AntDesign name="search1" size={24} color={'black'} />}
                />
            }
        />`

![Screenshot at Mar 15 15-17-24](https://user-images.githubusercontent.com/19631764/158410579-be98fefd-42e4-46fd-918b-82826bff8096.png)
